/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Cursor;
import view_TelaPesq.TlPesqArm;
import view_TelaPesq.TlPesqCautela;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import model.bean.Militar;
import net.sf.jasperreports.engine.JRException;
import servicos.Ajuda;
import servicos.AtualizarHora;
import servicos.Relatorio;
import view_TelaAlterar.TlAltEquipamento;
import view_TelaAlterar.TlAltMilitar;
import view_TelaAlterar.TlAltOM;
import view_TelaCadastro.TelaCadBaioneta;
import view_TelaCadastro.TlCadEquipamento;
import view_TelaAlterar.TlAltFuncaoMilitar;
import view_TelaCadastro.TlCadFuncaoMilitar;
import view_TelaCadastro.TlCadMilitar;
import view_TelaCadastro.TlCadOM;
import view_TelaPesq.TlPesqDescautelado;
import view_TelaPesq.TlPesqFuncao;
import view_TelaPesq.TlPesqMilitar;
import view_TelaPesq.TlPesqPartEntregue;
import view_TelaPesq.TlPesqPartRecebido;

/**
 *
 * @author ASUS
 */
public class TelaPrincipal extends javax.swing.JFrame {

    public int codigoArmeiro;

    Militar mi = new Militar();
    private TlCadFuncaoMilitar cadfuncaomilitar;
    private TlCadMilitar cadmilitar;
    private TlCadEquipamento cadequipamento;
    private TlCadOM cadom;
    private TelaCadBaioneta cadbaionte;
    private TlAltEquipamento altequipamento;
    private TlAltFuncaoMilitar altfuncaomilitar;
    private TlAltMilitar altmilitar;
    private TlAltOM altom;
    private TlDescautela descautela;
    private TlCautela cautela;
    private TlRelatorio relatorio;
    private TelaLogin login;
    private TlHistoricoMilitar historico;
    private TlHistoricoEquipamento historicoEquipamento;
    private TlCadEqpParticular particular;
    private TlSaidaEqpParticular particularsaida;
    private TlPesqPartRecebido particularRecebido;
    private TlPesqPartEntregue particularEntregue;
    private TlPesqDescautelado pesqdescautelado;
    private TlPesqArm pesarma;
    private TlPesqMilitar pesqmilitar;
    private TlPesqFuncao pesqfuncao;
    private TlPesqCautela pesqcautela;
    private TlCautelaMilitar cautelaMilitar;

    public TelaPrincipal(Militar mil) {
        initComponents();
        setIcon();
        setExtendedState(MAXIMIZED_BOTH); // Abrir a tela de forma maximizadaaa
        setTitle("Sistema da Reserva de Armamento // ARMEIRO: " + mil.getLogin());
        codigoArmeiro = mil.getIdarmeiro().getId();
        mostrarHora();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        jTextField1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jlhora = new javax.swing.JLabel();
        ImageIcon icon = new ImageIcon(getClass().getResource("/iconeSisArma/fundocigs.png"));
        final Image image = icon.getImage();
        jDesktop = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        }
        ;
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuCadMil = new javax.swing.JMenuItem();
        jMenuCadEqp = new javax.swing.JMenuItem();
        jMenuCadBai = new javax.swing.JMenuItem();
        jMenuFuncao = new javax.swing.JMenuItem();
        jMenuCadOm = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuAltMil = new javax.swing.JMenuItem();
        jMenuAltEqp = new javax.swing.JMenuItem();
        jMenuAltFun = new javax.swing.JMenuItem();
        jMenuAltOm = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuPesArm = new javax.swing.JMenuItem();
        jMenuPesqMilitar = new javax.swing.JMenuItem();
        jMenuPesqFuncao = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuParticularRecebido = new javax.swing.JMenuItem();
        jMenuParticularEntregue = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuCautelasCautelado = new javax.swing.JMenuItem();
        jMenuCautelasDescautelado = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuCautela = new javax.swing.JMenuItem();
        jMenuDescautelar = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jParticularItemEntrada = new javax.swing.JMenuItem();
        jParticularItemSaida = new javax.swing.JMenuItem();
        jMenuRelatório = new javax.swing.JMenu();
        jMenuRelatorio = new javax.swing.JMenuItem();
        jMenuCautelas = new javax.swing.JMenu();
        jMenuItemaCautelado = new javax.swing.JMenuItem();
        jMenuItemDescautelado = new javax.swing.JMenuItem();
        jMenuItemRelatorioPorData = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuAltDados = new javax.swing.JMenu();
        jMenuItemMilitar = new javax.swing.JMenuItem();
        jMenuItemEquipamento = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItemAtivos = new javax.swing.JMenuItem();
        jMenuItemInativos = new javax.swing.JMenuItem();
        jMenuItemHistoricoMilitar = new javax.swing.JMenuItem();
        jMenuItemHistoricoEquipamento = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuLogin = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Controle da Armaria");
        setBackground(new java.awt.Color(0, 255, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        setForeground(new java.awt.Color(51, 255, 0));
        setIconImages(null);

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setRollover(true);
        jToolBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("TODOS OS DIREITOS RESERVADOS © - CARLOS R T ARAÚJO  &  EDIELE A GONÇALVES - 2017 - Versão 2.6.1   ");
        jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField1.setPreferredSize(new java.awt.Dimension(649, 200));
        jToolBar1.add(jTextField1);
        jToolBar1.add(jSeparator3);

        jlhora.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jlhora.setText("Hora");
        jlhora.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jToolBar1.add(jlhora);

        jDesktop.setBackground(new java.awt.Color(153, 153, 153));
        jDesktop.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktop.setLayout(new javax.swing.OverlayLayout(jDesktop));

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(452, 40));

        jMenu1.setBorder(null);
        jMenu1.setText("Cadastrar");
        jMenu1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N

        jMenuCadMil.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCadMil.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuCadMil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/soldado.png"))); // NOI18N
        jMenuCadMil.setText("Militar");
        jMenuCadMil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadMilActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCadMil);

        jMenuCadEqp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCadEqp.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuCadEqp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/tanque.png"))); // NOI18N
        jMenuCadEqp.setText("Equipamento");
        jMenuCadEqp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadEqpActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCadEqp);

        jMenuCadBai.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCadBai.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuCadBai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/baioneta.png"))); // NOI18N
        jMenuCadBai.setText("Baioneta");
        jMenuCadBai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadBaiActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCadBai);

        jMenuFuncao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuFuncao.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/general.png"))); // NOI18N
        jMenuFuncao.setText("Função");
        jMenuFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFuncaoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuFuncao);

        jMenuCadOm.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCadOm.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuCadOm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/quartel.png"))); // NOI18N
        jMenuCadOm.setText("OM");
        jMenuCadOm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadOmActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCadOm);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Alterar");
        jMenu2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N

        jMenuAltMil.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jMenuAltMil.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuAltMil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/soldado.png"))); // NOI18N
        jMenuAltMil.setText("Militar");
        jMenuAltMil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAltMilActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuAltMil);

        jMenuAltEqp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jMenuAltEqp.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuAltEqp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/tanque.png"))); // NOI18N
        jMenuAltEqp.setText("Equipamento");
        jMenuAltEqp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAltEqpActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuAltEqp);

        jMenuAltFun.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        jMenuAltFun.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuAltFun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/general.png"))); // NOI18N
        jMenuAltFun.setText("Função");
        jMenuAltFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAltFunActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuAltFun);

        jMenuAltOm.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        jMenuAltOm.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuAltOm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/quartel.png"))); // NOI18N
        jMenuAltOm.setText("OM");
        jMenuAltOm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAltOmActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuAltOm);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Pesquisar");
        jMenu5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N

        jMenuPesArm.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuPesArm.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuPesArm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/arma.png"))); // NOI18N
        jMenuPesArm.setText("Equipamento");
        jMenuPesArm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPesArmActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuPesArm);

        jMenuPesqMilitar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuPesqMilitar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuPesqMilitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/troca.png"))); // NOI18N
        jMenuPesqMilitar.setText("Militar");
        jMenuPesqMilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPesqMilitarActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuPesqMilitar);

        jMenuPesqFuncao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuPesqFuncao.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuPesqFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/general.png"))); // NOI18N
        jMenuPesqFuncao.setText("Função");
        jMenuPesqFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPesqFuncaoActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuPesqFuncao);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/soldado.png"))); // NOI18N
        jMenu9.setText("Particular");
        jMenu9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        jMenuParticularRecebido.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuParticularRecebido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/descautelando.png"))); // NOI18N
        jMenuParticularRecebido.setText("Recebido ");
        jMenuParticularRecebido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuParticularRecebidoActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuParticularRecebido);

        jMenuParticularEntregue.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuParticularEntregue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/cautelando.png"))); // NOI18N
        jMenuParticularEntregue.setText("Entregue");
        jMenuParticularEntregue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuParticularEntregueActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuParticularEntregue);

        jMenu5.add(jMenu9);

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/cautela.png"))); // NOI18N
        jMenu10.setText("Cautelas");
        jMenu10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        jMenuCautelasCautelado.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuCautelasCautelado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/cautelando.png"))); // NOI18N
        jMenuCautelasCautelado.setText("Cautelado ");
        jMenuCautelasCautelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCautelasCauteladoActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuCautelasCautelado);

        jMenuCautelasDescautelado.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuCautelasDescautelado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/descautelando.png"))); // NOI18N
        jMenuCautelasDescautelado.setText("Descautelado");
        jMenuCautelasDescautelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCautelasDescauteladoActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuCautelasDescautelado);

        jMenu5.add(jMenu10);

        jMenuBar1.add(jMenu5);

        jMenu3.setText("Registrar");
        jMenu3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N

        jMenuCautela.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuCautela.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuCautela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/cautelando.png"))); // NOI18N
        jMenuCautela.setText("Cautela");
        jMenuCautela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCautelaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuCautela);

        jMenuDescautelar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuDescautelar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuDescautelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/descautelando.png"))); // NOI18N
        jMenuDescautelar.setText("Descautela");
        jMenuDescautelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDescautelarActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuDescautelar);

        jMenuBar1.add(jMenu3);

        jMenu8.setText("Particular");
        jMenu8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N

        jParticularItemEntrada.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jParticularItemEntrada.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jParticularItemEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/arma.png"))); // NOI18N
        jParticularItemEntrada.setText("Entrada");
        jParticularItemEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jParticularItemEntradaActionPerformed(evt);
            }
        });
        jMenu8.add(jParticularItemEntrada);

        jParticularItemSaida.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jParticularItemSaida.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jParticularItemSaida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/baioneta.png"))); // NOI18N
        jParticularItemSaida.setText("Saída");
        jParticularItemSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jParticularItemSaidaActionPerformed(evt);
            }
        });
        jMenu8.add(jParticularItemSaida);

        jMenuBar1.add(jMenu8);

        jMenuRelatório.setText("Relatório");
        jMenuRelatório.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N

        jMenuRelatorio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuRelatorio.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/pdf.png"))); // NOI18N
        jMenuRelatorio.setText("Pronto Reserva");
        jMenuRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRelatorioActionPerformed(evt);
            }
        });
        jMenuRelatório.add(jMenuRelatorio);

        jMenuCautelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/cautela.png"))); // NOI18N
        jMenuCautelas.setText("Cautelas");
        jMenuCautelas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        jMenuItemaCautelado.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuItemaCautelado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/cautelando.png"))); // NOI18N
        jMenuItemaCautelado.setText("Cautelado");
        jMenuItemaCautelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemaCauteladoActionPerformed(evt);
            }
        });
        jMenuCautelas.add(jMenuItemaCautelado);

        jMenuItemDescautelado.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuItemDescautelado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/descautelando.png"))); // NOI18N
        jMenuItemDescautelado.setText("Descautelado");
        jMenuItemDescautelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDescauteladoActionPerformed(evt);
            }
        });
        jMenuCautelas.add(jMenuItemDescautelado);

        jMenuItemRelatorioPorData.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuItemRelatorioPorData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/relogio.png"))); // NOI18N
        jMenuItemRelatorioPorData.setText("Por Data");
        jMenuItemRelatorioPorData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatorioPorDataActionPerformed(evt);
            }
        });
        jMenuCautelas.add(jMenuItemRelatorioPorData);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/soldado.png"))); // NOI18N
        jMenuItem2.setText("Militar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuCautelas.add(jMenuItem2);

        jMenuRelatório.add(jMenuCautelas);

        jMenuAltDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/troca.png"))); // NOI18N
        jMenuAltDados.setText("Alterações de Dados");
        jMenuAltDados.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        jMenuItemMilitar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuItemMilitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/soldado.png"))); // NOI18N
        jMenuItemMilitar.setText("Militar");
        jMenuItemMilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMilitarActionPerformed(evt);
            }
        });
        jMenuAltDados.add(jMenuItemMilitar);

        jMenuItemEquipamento.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuItemEquipamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/tanque.png"))); // NOI18N
        jMenuItemEquipamento.setText("Equipamento");
        jMenuItemEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEquipamentoActionPerformed(evt);
            }
        });
        jMenuAltDados.add(jMenuItemEquipamento);

        jMenuRelatório.add(jMenuAltDados);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/general.png"))); // NOI18N
        jMenu7.setText("Dados Militar");
        jMenu7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        jMenuItemAtivos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuItemAtivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/sim.png"))); // NOI18N
        jMenuItemAtivos.setText("Ativos");
        jMenuItemAtivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAtivosActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItemAtivos);

        jMenuItemInativos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuItemInativos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/nao.png"))); // NOI18N
        jMenuItemInativos.setText("Inativos");
        jMenuItemInativos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInativosActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItemInativos);

        jMenuRelatório.add(jMenu7);

        jMenuItemHistoricoMilitar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuItemHistoricoMilitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/soldado.png"))); // NOI18N
        jMenuItemHistoricoMilitar.setText("Histórico Militar");
        jMenuItemHistoricoMilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHistoricoMilitarActionPerformed(evt);
            }
        });
        jMenuRelatório.add(jMenuItemHistoricoMilitar);

        jMenuItemHistoricoEquipamento.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuItemHistoricoEquipamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/tanque.png"))); // NOI18N
        jMenuItemHistoricoEquipamento.setText("Histórico Equipamento");
        jMenuItemHistoricoEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHistoricoEquipamentoActionPerformed(evt);
            }
        });
        jMenuRelatório.add(jMenuItemHistoricoEquipamento);

        jMenuBar1.add(jMenuRelatório);

        jMenu6.setText("Ajuda");
        jMenu6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });

        jMenuItem1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/pdf.png"))); // NOI18N
        jMenuItem1.setText("Manual");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenuBar1.add(jMenu6);

        jMenu4.setText("Sair");
        jMenu4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N

        jMenuLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuLogin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/troca.png"))); // NOI18N
        jMenuLogin.setText("Trocar Usuário");
        jMenuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLoginActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuLogin);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/desliga.png"))); // NOI18N
        jMenuItem3.setText("Desligar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addGap(26, 26, 26)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCadBaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadBaiActionPerformed
        cadbaionte = new TelaCadBaioneta(codigoArmeiro);
        removeTela(cadbaionte);
    }//GEN-LAST:event_jMenuCadBaiActionPerformed

    private void jMenuCadMilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadMilActionPerformed
        cadmilitar = new TlCadMilitar(codigoArmeiro);
        removeTela(cadmilitar);

    }//GEN-LAST:event_jMenuCadMilActionPerformed

    private void jMenuCadEqpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadEqpActionPerformed
        cadequipamento = new TlCadEquipamento(codigoArmeiro);
        removeTela(cadequipamento);
    }//GEN-LAST:event_jMenuCadEqpActionPerformed

    private void jMenuPesArmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPesArmActionPerformed
        pesarma = new TlPesqArm();
        removeTela(pesarma);
    }//GEN-LAST:event_jMenuPesArmActionPerformed

    private void jMenuCadOmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadOmActionPerformed
        cadom = new TlCadOM();
        removeTela(cadom);
    }//GEN-LAST:event_jMenuCadOmActionPerformed

    private void jMenuAltMilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAltMilActionPerformed
        altmilitar = new TlAltMilitar(this.codigoArmeiro);
        removeTela(altmilitar);
    }//GEN-LAST:event_jMenuAltMilActionPerformed

    private void jMenuAltEqpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAltEqpActionPerformed
        altequipamento = new TlAltEquipamento(this.codigoArmeiro);
        removeTela(altequipamento);
    }//GEN-LAST:event_jMenuAltEqpActionPerformed

    private void jMenuAltFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAltFunActionPerformed
        altfuncaomilitar = new TlAltFuncaoMilitar();
        removeTela(altfuncaomilitar);
    }//GEN-LAST:event_jMenuAltFunActionPerformed

    private void jMenuAltOmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAltOmActionPerformed
        altom = new TlAltOM();
        removeTela(altom);
    }//GEN-LAST:event_jMenuAltOmActionPerformed

    private void jMenuRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRelatorioActionPerformed
        relatorio = new TlRelatorio(this.codigoArmeiro);
        removeTela(relatorio);
    }//GEN-LAST:event_jMenuRelatorioActionPerformed

    private void jMenuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLoginActionPerformed
        login = new TelaLogin();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuLoginActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        String str = "shutdown.exe -s -t 0";
        try {
            Runtime.getRuntime().exec(str);
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuPesqMilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPesqMilitarActionPerformed
        pesqmilitar = new TlPesqMilitar();
        removeTela(pesqmilitar);
    }//GEN-LAST:event_jMenuPesqMilitarActionPerformed

    private void jMenuPesqFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPesqFuncaoActionPerformed
        pesqfuncao = new TlPesqFuncao();
        removeTela(pesqfuncao);

    }//GEN-LAST:event_jMenuPesqFuncaoActionPerformed

    private void jMenuItemMilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMilitarActionPerformed
        Relatorio rl = new Relatorio();
        try {
            Cursor cursor = Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR);
            jDesktop.setCursor(cursor);
            rl.relatorioAlteracaoUsuario();
            cursor = Cursor.getDefaultCursor();
            jDesktop.setCursor(cursor);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "ERRO AO GERAR RELATÓRIO - CHAMAR STI");
            System.out.println(ex);
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItemMilitarActionPerformed

    private void jMenuItemEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEquipamentoActionPerformed
        Relatorio rl = new Relatorio();
        try {
            Cursor cursor = Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR);
            jDesktop.setCursor(cursor);
            rl.relatorioAlteracaoEquipamento();
            cursor = Cursor.getDefaultCursor();
            jDesktop.setCursor(cursor);

        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "ERRO AO GERAR RELATÓRIO");
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            dispose();
        }
    }//GEN-LAST:event_jMenuItemEquipamentoActionPerformed

    private void jMenuItemHistoricoMilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHistoricoMilitarActionPerformed
        historico = new TlHistoricoMilitar(null, rootPaneCheckingEnabled);
        historico.setVisible(true);
    }//GEN-LAST:event_jMenuItemHistoricoMilitarActionPerformed

    private void jMenuItemHistoricoEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHistoricoEquipamentoActionPerformed
        historicoEquipamento = new TlHistoricoEquipamento(null, rootPaneCheckingEnabled);
        historicoEquipamento.setVisible(true);
    }//GEN-LAST:event_jMenuItemHistoricoEquipamentoActionPerformed

    private void jMenuItemaCauteladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemaCauteladoActionPerformed
        Relatorio rl = new Relatorio();
        try {
            Cursor cursor = Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR);
            jDesktop.setCursor(cursor);
            rl.relatorioEquipamentoCautelado();
            cursor = Cursor.getDefaultCursor();
            jDesktop.setCursor(cursor);

        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "ERRO AO GERAR RELATÓRIO");
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemaCauteladoActionPerformed

    private void jMenuItemDescauteladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDescauteladoActionPerformed
        Relatorio rl = new Relatorio();
        try {
            Cursor cursor = Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR);
            jDesktop.setCursor(cursor);
            rl.relatorioEquipamentoDescautelados();
            cursor = Cursor.getDefaultCursor();
            jDesktop.setCursor(cursor);

        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "ERRO AO GERAR RELATÓRIO");
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemDescauteladoActionPerformed

    private void jMenuItemAtivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAtivosActionPerformed
        Relatorio rl = new Relatorio();
        try {
            Cursor cursor = Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR);
            jDesktop.setCursor(cursor);
            rl.militarAtivo();
            cursor = Cursor.getDefaultCursor();
            jDesktop.setCursor(cursor);

        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "ERRO AO GERAR RELATÓRIO");
            System.out.println(ex);
        }

    }//GEN-LAST:event_jMenuItemAtivosActionPerformed

    private void jMenuItemRelatorioPorDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatorioPorDataActionPerformed
        TlData tl = new TlData(null, rootPaneCheckingEnabled);
        tl.setVisible(true);
    }//GEN-LAST:event_jMenuItemRelatorioPorDataActionPerformed

    private void jMenuItemInativosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInativosActionPerformed
        Relatorio rl = new Relatorio();
        try {
            Cursor cursor = Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR);
            jDesktop.setCursor(cursor);
            rl.militarInativo();
            cursor = Cursor.getDefaultCursor();
            jDesktop.setCursor(cursor);

        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "ERRO AO GERAR RELATÓRIO");
            System.out.println(ex);
        }
    }//GEN-LAST:event_jMenuItemInativosActionPerformed

    private void jMenuFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFuncaoActionPerformed
        cadfuncaomilitar = new TlCadFuncaoMilitar();
        removeTela(cadfuncaomilitar);
    }//GEN-LAST:event_jMenuFuncaoActionPerformed

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
        TlAjuda tl = new TlAjuda();
        jDesktop.add(tl);
        tl.setVisible(true);

    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jMenuDescautelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDescautelarActionPerformed
        descautela = new TlDescautela(this.codigoArmeiro);
        removeTela(descautela);
    }//GEN-LAST:event_jMenuDescautelarActionPerformed

    private void jMenuCautelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCautelaActionPerformed
        cautela = new TlCautela(this.codigoArmeiro);
        removeTela(cautela);
    }//GEN-LAST:event_jMenuCautelaActionPerformed

    private void jParticularItemEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jParticularItemEntradaActionPerformed
        particular = new TlCadEqpParticular(codigoArmeiro);
        removeTela(particular);
    }//GEN-LAST:event_jParticularItemEntradaActionPerformed

    private void jParticularItemSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jParticularItemSaidaActionPerformed
        particularsaida = new TlSaidaEqpParticular(codigoArmeiro);
        removeTela(particularsaida);
    }//GEN-LAST:event_jParticularItemSaidaActionPerformed

    private void jMenuParticularEntregueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuParticularEntregueActionPerformed
        particularEntregue = new TlPesqPartEntregue();
        removeTela(particularEntregue);
    }//GEN-LAST:event_jMenuParticularEntregueActionPerformed

    private void jMenuParticularRecebidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuParticularRecebidoActionPerformed
        particularRecebido = new TlPesqPartRecebido();
        removeTela(particularRecebido);
    }//GEN-LAST:event_jMenuParticularRecebidoActionPerformed

    private void jMenuCautelasDescauteladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCautelasDescauteladoActionPerformed
        pesqdescautelado = new TlPesqDescautelado();
        removeTela(pesqdescautelado);
    }//GEN-LAST:event_jMenuCautelasDescauteladoActionPerformed

    private void jMenuCautelasCauteladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCautelasCauteladoActionPerformed
        pesqcautela = new TlPesqCautela();
        removeTela(pesqcautela);
    }//GEN-LAST:event_jMenuCautelasCauteladoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Ajuda ajuda = new Ajuda();
        ajuda.abrirPDF();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        cautelaMilitar = new TlCautelaMilitar(null, rootPaneCheckingEnabled);
        cautelaMilitar.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public final void mostrarHora() {
        AtualizarHora ah = new AtualizarHora(jlhora);
        ah.mostrarData(true);
        Thread thHora = ah;
        thHora.start();
    }

    public void removeTela(JInternalFrame nova) {
        for (JInternalFrame jInternalFrame : this.jDesktop.getAllFrames()) {
            try {
                jInternalFrame.setClosed(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        jDesktop.add(nova);
        nova.setVisible(true);
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/iconeSisArma/brasil16.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JDesktopPane jDesktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenu jMenuAltDados;
    private javax.swing.JMenuItem jMenuAltEqp;
    private javax.swing.JMenuItem jMenuAltFun;
    private javax.swing.JMenuItem jMenuAltMil;
    private javax.swing.JMenuItem jMenuAltOm;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCadBai;
    private javax.swing.JMenuItem jMenuCadEqp;
    private javax.swing.JMenuItem jMenuCadMil;
    private javax.swing.JMenuItem jMenuCadOm;
    private javax.swing.JMenuItem jMenuCautela;
    private javax.swing.JMenu jMenuCautelas;
    private javax.swing.JMenuItem jMenuCautelasCautelado;
    private javax.swing.JMenuItem jMenuCautelasDescautelado;
    private javax.swing.JMenuItem jMenuDescautelar;
    private javax.swing.JMenuItem jMenuFuncao;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemAtivos;
    private javax.swing.JMenuItem jMenuItemDescautelado;
    private javax.swing.JMenuItem jMenuItemEquipamento;
    private javax.swing.JMenuItem jMenuItemHistoricoEquipamento;
    private javax.swing.JMenuItem jMenuItemHistoricoMilitar;
    private javax.swing.JMenuItem jMenuItemInativos;
    private javax.swing.JMenuItem jMenuItemMilitar;
    private javax.swing.JMenuItem jMenuItemRelatorioPorData;
    private javax.swing.JMenuItem jMenuItemaCautelado;
    private javax.swing.JMenuItem jMenuLogin;
    private javax.swing.JMenuItem jMenuParticularEntregue;
    private javax.swing.JMenuItem jMenuParticularRecebido;
    private javax.swing.JMenuItem jMenuPesArm;
    private javax.swing.JMenuItem jMenuPesqFuncao;
    private javax.swing.JMenuItem jMenuPesqMilitar;
    private javax.swing.JMenuItem jMenuRelatorio;
    private javax.swing.JMenu jMenuRelatório;
    private javax.swing.JMenuItem jParticularItemEntrada;
    private javax.swing.JMenuItem jParticularItemSaida;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel jlhora;
    // End of variables declaration//GEN-END:variables
}
