/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view_TelaCadastro;

import java.awt.Color;
import javax.swing.JOptionPane;
import model.bean.Categoria;
import model.bean.Equipamento;
import model.bean.FuncaoMilitar;
import model.dao.EquipamentoDao;

/**
 *
 * @author Asus
 */
public class TelaCadBaioneta extends javax.swing.JInternalFrame {

    Integer codigoArmeiro;

    public TelaCadBaioneta(int codigoArmeiro) {
        initComponents();
        this.codigoArmeiro = codigoArmeiro;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLbaioneta = new javax.swing.JLabel();
        jTSerie = new javax.swing.JTextField();
        jButtoncanelar = new javax.swing.JButton();
        jButtonsalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setFrameIcon(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16))); // NOI18N

        jLbaioneta.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLbaioneta.setText("Baioneta:");

        jTSerie.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTSerieActionPerformed(evt);
            }
        });

        jButtoncanelar.setBackground(new java.awt.Color(242, 67, 56));
        jButtoncanelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtoncanelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/cancela32.png"))); // NOI18N
        jButtoncanelar.setText("CANCELAR");
        jButtoncanelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncanelarActionPerformed(evt);
            }
        });

        jButtonsalvar.setBackground(new java.awt.Color(75, 184, 75));
        jButtonsalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/salvar.png"))); // NOI18N
        jButtonsalvar.setText("  SALVAR");
        jButtonsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsalvarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Informe apenas o número da Baioneta!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jButtoncanelar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jButtonsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbaioneta)
                            .addComponent(jTSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbaioneta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtoncanelar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTSerieActionPerformed
        cadastrar();
    }//GEN-LAST:event_jTSerieActionPerformed

    private void jButtoncanelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncanelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtoncanelarActionPerformed

    private void jButtonsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsalvarActionPerformed

        cadastrar();
    }//GEN-LAST:event_jButtonsalvarActionPerformed

    private void cadastrar() {
        Equipamento eqp = new Equipamento();
        EquipamentoDao eqpDao = new EquipamentoDao();

        eqp.setSerie("B" + jTSerie.getText());
        eqp.setNome("BAIONETA");
        eqp.setStatus("DISPONIVEL");
        eqp.setQtd(1);
        eqp.setTipo("AC");
        Categoria categoria = new Categoria();
        categoria.setId(1);
        eqp.setCategoria(categoria);
        FuncaoMilitar armeiro = new FuncaoMilitar();
        armeiro.setId(codigoArmeiro);
        eqp.setArmeiro(armeiro);
        try {
            if (validarCampo() == false) {
                JOptionPane.showMessageDialog(null, "Campo Obrigatório");
                jLbaioneta.setForeground(Color.red);
            } else {
                eqpDao.cadastrarAcessorio(eqp);
                JOptionPane.showMessageDialog(null, " CADASTRADA ");
                limparCampo();
            }
        } catch (Exception ex) {
            System.out.println("Erro ao cadastrar" + ex.getMessage());

        }
    }

    private void limparCampo() {
        jTSerie.setText("");
    }

    private boolean validarCampo() {
        boolean valida = true;
        if (jTSerie.getText().equals("")) {
            valida = false;
        }
        return valida;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoncanelar;
    private javax.swing.JButton jButtonsalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbaioneta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTSerie;
    // End of variables declaration//GEN-END:variables
}
