/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view_TelaCadastro;

import Controller.ControllerMilitar;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import model.bean.FuncaoMilitar;
import model.bean.Graduacao;
import model.bean.Militar;
import model.bean.OM;
import model.dao.GraduacaoDao;
import model.dao.MilitarDao;
import model.dao.OMDao;
import servicos.CisBiox;
import servicos.LimitaTexto;
import servicos.Maiusculas;
import servicos.Numero;

/**
 *
 * @author ASUS
 */
public class TlCadMilitar extends javax.swing.JInternalFrame {

    CisBiox biox = new CisBiox();
    private byte[] digital;
    private byte[] digital2;
    Integer codigoArmeiro;

    public TlCadMilitar(int codigoArmeiro) {

        initComponents();
        listarOM(jComboBoxom); // metodos para listar todas as OM assim que a tela for chamada
        listarGraduacao(jComboBoxgraduacao);   // metodos para listar todas as OM assim que a tela for chamada
        jTidentidade.setDocument(new Numero());
        jTidentidade.setDocument(new LimitaTexto(10));
        jTguerra.setDocument(new Maiusculas());
        jTnome.setDocument(new Maiusculas());
        jTlogin.setDocument(new Maiusculas());
        jPasswordsenha.setDocument(new Numero());
        jPasswordConfimacao.setDocument(new Numero());
        this.codigoArmeiro = codigoArmeiro;
        jTidentidade.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sexo = new javax.swing.ButtonGroup();
        Status = new javax.swing.ButtonGroup();
        jBsalvar = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTidentidade = new javax.swing.JTextField();
        jLnome = new javax.swing.JLabel();
        jLUsuario = new javax.swing.JLabel();
        jTlogin = new javax.swing.JTextField();
        jLsenha = new javax.swing.JLabel();
        jPasswordsenha = new javax.swing.JPasswordField();
        jLguerra = new javax.swing.JLabel();
        jTguerra = new javax.swing.JTextField();
        jLsexo = new javax.swing.JLabel();
        jRadiomasculino = new javax.swing.JRadioButton();
        jRadiofeminino = new javax.swing.JRadioButton();
        jLgraduacao = new javax.swing.JLabel();
        jComboBoxgraduacao = new javax.swing.JComboBox<>();
        jLom = new javax.swing.JLabel();
        jComboBoxom = new javax.swing.JComboBox<>();
        jLidentidade = new javax.swing.JLabel();
        jTnome = new javax.swing.JTextField();
        jPasswordConfimacao = new javax.swing.JPasswordField();
        jLconfirmarSenha = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonBiomatria = new javax.swing.JButton();
        jButtonBiomatria2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBcancelarBiometria = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setFrameIcon(null);
        setPreferredSize(new java.awt.Dimension(1387, 620));
        setVisible(true);

        jBsalvar.setBackground(new java.awt.Color(75, 184, 75));
        jBsalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/salvar.png"))); // NOI18N
        jBsalvar.setText("SALVAR");
        jBsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarActionPerformed(evt);
            }
        });

        jBcancelar.setBackground(new java.awt.Color(242, 67, 56));
        jBcancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/cancela32.png"))); // NOI18N
        jBcancelar.setText("CANCELAR");
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16))); // NOI18N

        jTidentidade.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jTidentidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTidentidadeKeyReleased(evt);
            }
        });

        jLnome.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLnome.setText("Nome Completo:");

        jLUsuario.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLUsuario.setText("Usuário:");

        jTlogin.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTlogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTloginKeyReleased(evt);
            }
        });

        jLsenha.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLsenha.setText("Senha:");

        jPasswordsenha.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jPasswordsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordsenhaActionPerformed(evt);
            }
        });
        jPasswordsenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordsenhaKeyTyped(evt);
            }
        });

        jLguerra.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLguerra.setText("Nome de Guerra:");

        jTguerra.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTguerra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTguerraKeyReleased(evt);
            }
        });

        jLsexo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLsexo.setText("Sexo: ");

        Sexo.add(jRadiomasculino);
        jRadiomasculino.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadiomasculino.setSelected(true);
        jRadiomasculino.setText("Masculino");

        Sexo.add(jRadiofeminino);
        jRadiofeminino.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadiofeminino.setText("Feminino");

        jLgraduacao.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLgraduacao.setText("Posto / Graduação:");

        jComboBoxgraduacao.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboBoxgraduacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Posto / Graduação" }));

        jLom.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLom.setText("Organização Militar:");

        jComboBoxom.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboBoxom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Organização Militar" }));

        jLidentidade.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLidentidade.setText("Identidade Militar:");

        jTnome.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTnomeKeyReleased(evt);
            }
        });

        jPasswordConfimacao.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jPasswordConfimacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordConfimacaoFocusLost(evt);
            }
        });
        jPasswordConfimacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordConfimacaoKeyTyped(evt);
            }
        });

        jLconfirmarSenha.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLconfirmarSenha.setText("Confirmar Senha:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados Biométrico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16))); // NOI18N

        jButtonBiomatria.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonBiomatria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/ler_biometria.png"))); // NOI18N
        jButtonBiomatria.setBorderPainted(false);
        jButtonBiomatria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBiomatriaActionPerformed(evt);
            }
        });

        jButtonBiomatria2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonBiomatria2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/ler_biometria.png"))); // NOI18N
        jButtonBiomatria2.setBorderPainted(false);
        jButtonBiomatria2.setEnabled(false);
        jButtonBiomatria2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBiomatria2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel1.setText("Inserir polegar direito:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setText("Inserir polegar direito:");

        jBcancelarBiometria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/cancelar_biometria.png"))); // NOI18N
        jBcancelarBiometria.setBorder(null);
        jBcancelarBiometria.setBorderPainted(false);
        jBcancelarBiometria.setEnabled(false);
        jBcancelarBiometria.setFocusPainted(false);
        jBcancelarBiometria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarBiometriaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setText("Cancelar leitura:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBcancelarBiometria, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBiomatria, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonBiomatria2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBiomatria)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBiomatria2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBcancelarBiometria, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLgraduacao)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxgraduacao, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLidentidade)
                                    .addComponent(jLnome))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTidentidade, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLguerra, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTguerra, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLsenha)
                                                .addComponent(jLsexo, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(jLUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jPasswordsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLconfirmarSenha))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jRadiomasculino)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jRadiofeminino))
                                            .addComponent(jTlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPasswordConfimacao, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(145, 145, 145)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTidentidade, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLidentidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLnome))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTguerra, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLguerra))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLUsuario)
                            .addComponent(jTlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLsenha)
                            .addComponent(jPasswordsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordConfimacao, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLconfirmarSenha))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLsexo)
                            .addComponent(jRadiomasculino)
                            .addComponent(jRadiofeminino))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLgraduacao)
                            .addComponent(jComboBoxgraduacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLom)
                            .addComponent(jComboBoxom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jBsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBsalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBcancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarActionPerformed
        MilitarDao mdao = new MilitarDao();
        String identidade = jTidentidade.getText();
        if (validaCampo()) {
            try {
                int i = mdao.pesqIdentidade(identidade);
                if (i == 2) {
                    JOptionPane.showMessageDialog(null, "IDENTIDADE JÁ EXISTE!!!");
                    jTidentidade.setText("");
                } else {
                    Militar mil = new Militar();
                    ControllerMilitar controle = new ControllerMilitar();
                    String status = "ATIVO";
                    Graduacao gra = (Graduacao) jComboBoxgraduacao.getSelectedItem();
                    mil.setGraduacao(gra);
                    OM om = (OM) jComboBoxom.getSelectedItem();
                    mil.setOm(om);
                    mil.setIdmilitar(jTidentidade.getText());
                    mil.setNome(jTnome.getText());
                    mil.setGuerra(jTguerra.getText());
                    mil.setLogin(jTlogin.getText());
                    mil.setSenha(jPasswordsenha.getText());
                    mil.setSexo(getSexo());
                    mil.setStatus(status);
                    mil.setDigital(digital);
                    FuncaoMilitar armeiro = new FuncaoMilitar();
                    armeiro.setId(codigoArmeiro);
                    mil.setIdarmeiro(armeiro);
                    try {
                        controle.cadastrar(mil);
                        JOptionPane.showMessageDialog(null, "CADASTRADO!");
                        dispose();
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, "NÃO CADASTRADO!!!");
                        JOptionPane.showMessageDialog(null, ex.getMessage());
                        System.out.println("ERRO" + ex.getMessage());
                        limparCampos();
                    }
                }
            } catch (Exception ex) {
                Logger.getLogger(TlCadMilitar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jBsalvarActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jButtonBiomatriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBiomatriaActionPerformed
        jBcancelarBiometria.setEnabled(true);
        new Thread() {
            public void run() {
                try {
                    int iRetorno = biox.iniciar();
                    if (iRetorno != 1) {
                        JOptionPane.showMessageDialog(null, "Erro: " + CisBiox.mensagens(iRetorno));
                        return;
                    }
                    digital = biox.capturarDigital();
                    if (biox.getResultado() != 1) {
                        biox.finalizar();
                        return;
                    }
                    iRetorno = biox.finalizar();
                    if (iRetorno != 1) {
                        JOptionPane.showMessageDialog(null, "Erro: " + CisBiox.mensagens(iRetorno));
                        return;
                    }
                    JOptionPane.showMessageDialog(null, "CAPTURADA!");
                    jButtonBiomatria.setEnabled(false);
                    jButtonBiomatria2.setEnabled(true);
                } catch (Exception e) {
                    System.out.println("Erro ainda nao sei " + e.getMessage());
                }
            }
        ;
    }.start();
    }//GEN-LAST:event_jButtonBiomatriaActionPerformed

    private void jButtonBiomatria2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBiomatria2ActionPerformed
        jBcancelarBiometria.setEnabled(true);
        new Thread() {
            public void run() {
                try {
                    int iRetorno = biox.iniciar();
                    if (iRetorno != 1) {
                        JOptionPane.showMessageDialog(null, "Erro: " + CisBiox.mensagens(iRetorno));
                        return;
                    }
                    digital2 = biox.capturarDigital();
                    if (biox.getResultado() != 1) {
                        biox.finalizar();
                        return;
                    }
                    iRetorno = biox.finalizar();
                    if (iRetorno != 1) {
                        JOptionPane.showMessageDialog(null, "Erro: " + CisBiox.mensagens(iRetorno));
                        return;
                    }
                    leitura();
                    jButtonBiomatria2.setEnabled(false);
                } catch (Exception e) {
                    System.out.println("Erro ainda nao sei " + e.getMessage());
                }
            }
        ;
    }.start();
    }//GEN-LAST:event_jButtonBiomatria2ActionPerformed

    private void jBcancelarBiometriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarBiometriaActionPerformed
        CisBiox dll = new CisBiox();

        // Cancelar a leitura
        dll.cancelarLeitura();
        int iRetorno = biox.finalizar();
        if (iRetorno != 1) {
            JOptionPane.showMessageDialog(null, "Erro: " + CisBiox.mensagens(iRetorno));
            return;
        }
        jBcancelarBiometria.setEnabled(false);
        jButtonBiomatria.setEnabled(true);
        jButtonBiomatria2.setEnabled(true);
    }//GEN-LAST:event_jBcancelarBiometriaActionPerformed

    private void jPasswordsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordsenhaActionPerformed
        jPasswordConfimacao.requestFocus();

    }//GEN-LAST:event_jPasswordsenhaActionPerformed

    private void jTidentidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTidentidadeKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTnome.grabFocus();
        }
    }//GEN-LAST:event_jTidentidadeKeyReleased

    private void jTnomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTnomeKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTguerra.grabFocus();
        }
    }//GEN-LAST:event_jTnomeKeyReleased

    private void jTguerraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTguerraKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTlogin.grabFocus();
        }
    }//GEN-LAST:event_jTguerraKeyReleased

    private void jTloginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTloginKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jPasswordsenha.grabFocus();
        }
    }//GEN-LAST:event_jTloginKeyReleased

    private void jPasswordsenhaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordsenhaKeyTyped
        if (jPasswordsenha.getPassword().length > 5) {
            JOptionPane.showMessageDialog(this, "APENAS 6 NÚMEROS");
            evt.consume();
            jPasswordsenha.setText("");
            jPasswordsenha.grabFocus();
        }
    }//GEN-LAST:event_jPasswordsenhaKeyTyped

    private void jPasswordConfimacaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordConfimacaoKeyTyped
        if (jPasswordConfimacao.getPassword().length > 5) {
            JOptionPane.showMessageDialog(this, "APENAS 6 NÚMEROS");
            evt.consume();
            jPasswordConfimacao.setText("");
            jPasswordConfimacao.grabFocus();
        }
    }//GEN-LAST:event_jPasswordConfimacaoKeyTyped

    private void jPasswordConfimacaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordConfimacaoFocusLost
        if (jPasswordsenha.getText().equals(jPasswordConfimacao.getText())) {
            jRadiomasculino.requestFocus();
        } else {
            JOptionPane.showMessageDialog(null, "SENHAS DIFERENTES");
            jPasswordsenha.setText("");
            jPasswordConfimacao.setText("");
            jPasswordsenha.requestFocus();
        }
    }//GEN-LAST:event_jPasswordConfimacaoFocusLost

    private void leitura() {
        biox.iniciar();
        int iRetorno = biox.compararDigital(digital, digital2);
        switch (iRetorno) {
            case 1:
                JOptionPane.showMessageDialog(null, " DIGITAIS IGUAIS ");
                jButtonBiomatria2.setEnabled(false);
                break;
            case -2:
                JOptionPane.showMessageDialog(null, "! REPETIR !");
                jButtonBiomatria.setEnabled(true);
                break;
            default:
                JOptionPane.showMessageDialog(null, "Erro: " + CisBiox.mensagens(iRetorno));
                break;
        }

        biox.finalizar();
    }

    private void listarGraduacao(JComboBox combo) {

        try {
            List<Graduacao> lista = new GraduacaoDao().listEntidade();
            for (Graduacao g : lista) {
                combo.addItem(g);
            }
        } catch (Exception ex) {
            System.out.println("Erro ao listar Graduação:" + ex.getMessage());
        }

    }

    private void listarOM(JComboBox combo) {

        try {
            List<OM> lista = new OMDao().listEntidade();
            for (OM om : lista) {
                combo.addItem(om);
            }
        } catch (Exception ex) {
            System.out.println("Erro ao listar OM:" + ex.getMessage());
        }
    }

    private String getSexo() {
        String sexo = "M";
        if (jRadiofeminino.isSelected()) {
            sexo = "F";
        }
        return sexo;
    }

    public boolean validaCampo() {

        if (jTidentidade.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "CAMPO OBRIGATÓRIO");
            jLidentidade.setForeground(Color.red);
            jTidentidade.requestFocus();
            return false;

        }
        if (jTnome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "CAMPO OBRIGATÓRIO");
            jLnome.setForeground(Color.red);
            jTnome.requestFocus();
            return false;
        }
        if (jTguerra.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "CAMPO OBRIGATÓRIO");
            jLguerra.setForeground(Color.red);
            jTguerra.requestFocus();
            return false;

        }
        if (jTlogin.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "CAMPO OBRIGATÓRIO");
            jLUsuario.setForeground(Color.red);
            jTlogin.requestFocus();
            return false;
        }
        if (jPasswordsenha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "CAMPO OBRIGATÓRIO");
            jLsenha.setForeground(Color.red);
            jPasswordsenha.requestFocus();
            return false;

        }
        if (jPasswordConfimacao.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "CAMPO OBRIGATÓRIO");
            jLconfirmarSenha.setForeground(Color.red);
            jPasswordConfimacao.requestFocus();
            return false;
        }
        if (jComboBoxgraduacao.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "SELECIONE GRADUAÇÃO");
            jLgraduacao.setForeground(Color.red);
            return false;
        }
        if (jComboBoxom.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "SEELCIONE OM");
            jLom.setForeground(Color.red);
            return false;
        }
        if (digital == null) {
            JOptionPane.showMessageDialog(null, "CAPTURE BIOMATRIA 1");
            return false;
        }
        if (digital2 == null) {
            JOptionPane.showMessageDialog(null, "CAPTURE BIOMATRIA 2");
            return false;
        } else {
            return true;
        }
    }

    private void limparCampos() {
        jTidentidade.setText("");
        jTnome.setText("");
        jTguerra.setText("");
        jTlogin.setText("");
        jPasswordConfimacao.setText("");
        jPasswordsenha.setText("");
        jComboBoxgraduacao.setSelectedIndex(0);
        jComboBoxom.setSelectedIndex(0);
        jLsexo.setForeground(Color.black);
        jLsenha.setForeground(Color.black);
        jLom.setForeground(Color.black);
        jLnome.setForeground(Color.black);
        jLUsuario.setForeground(Color.black);
        jLidentidade.setForeground(Color.black);
        jLguerra.setForeground(Color.black);
        jLgraduacao.setForeground(Color.black);
        jLconfirmarSenha.setForeground(Color.black);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Sexo;
    private javax.swing.ButtonGroup Status;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JToggleButton jBcancelarBiometria;
    private javax.swing.JButton jBsalvar;
    private javax.swing.JButton jButtonBiomatria;
    private javax.swing.JButton jButtonBiomatria2;
    private javax.swing.JComboBox<String> jComboBoxgraduacao;
    private javax.swing.JComboBox<String> jComboBoxom;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLconfirmarSenha;
    private javax.swing.JLabel jLgraduacao;
    private javax.swing.JLabel jLguerra;
    private javax.swing.JLabel jLidentidade;
    private javax.swing.JLabel jLnome;
    private javax.swing.JLabel jLom;
    private javax.swing.JLabel jLsenha;
    private javax.swing.JLabel jLsexo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordConfimacao;
    private javax.swing.JPasswordField jPasswordsenha;
    private javax.swing.JRadioButton jRadiofeminino;
    private javax.swing.JRadioButton jRadiomasculino;
    private javax.swing.JTextField jTguerra;
    private javax.swing.JTextField jTidentidade;
    private javax.swing.JTextField jTlogin;
    private javax.swing.JTextField jTnome;
    // End of variables declaration//GEN-END:variables

}
