/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view_TelaCadastro;

import armaria.Armaria;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.bean.Funcao;
import model.bean.FuncaoMilitar;
import model.bean.Militar;
import model.dao.FuncaoMilitarDao;
import model.dao.MilitarDao;
import servicos.LimitaTexto;

/**
 *
 * @author ASUS
 */
public class TlCadFuncaoMilitar extends javax.swing.JInternalFrame {

    private Integer idMilitar;

    public TlCadFuncaoMilitar() {
        initComponents();
        jTidentidade.setDocument(new LimitaTexto(10));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StatusArmeiro = new javax.swing.ButtonGroup();
        StatusInspecionador = new javax.swing.ButtonGroup();
        StatusOficialDia = new javax.swing.ButtonGroup();
        jBcancelar = new javax.swing.JButton();
        jBsalvar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTidentidade = new javax.swing.JTextField();
        jLabelLoginMilitar = new javax.swing.JLabel();
        jBautenticar = new javax.swing.JButton();
        jRadioArmeiro = new javax.swing.JRadioButton();
        JRadioInspecionador = new javax.swing.JRadioButton();
        JRadioOficialDia = new javax.swing.JRadioButton();

        setBorder(null);
        setFrameIcon(null);

        jBcancelar.setBackground(new java.awt.Color(242, 67, 56));
        jBcancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/cancela32.png"))); // NOI18N
        jBcancelar.setText("CANCELAR");
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });

        jBsalvar.setBackground(new java.awt.Color(75, 184, 75));
        jBsalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/salvar.png"))); // NOI18N
        jBsalvar.setText("SALVAR");
        jBsalvar.setEnabled(false);
        jBsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados Função Militar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16))); // NOI18N

        jTidentidade.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTidentidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTidentidadeActionPerformed(evt);
            }
        });

        jLabelLoginMilitar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelLoginMilitar.setText("IDENTIDADE:");

        jBautenticar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBautenticar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/pesquisar.png"))); // NOI18N
        jBautenticar.setBorder(null);
        jBautenticar.setBorderPainted(false);
        jBautenticar.setContentAreaFilled(false);
        jBautenticar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBautenticarActionPerformed(evt);
            }
        });

        jRadioArmeiro.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadioArmeiro.setText("Armeiro");
        jRadioArmeiro.setEnabled(false);
        jRadioArmeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioArmeiroActionPerformed(evt);
            }
        });

        JRadioInspecionador.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        JRadioInspecionador.setText("Inspecionador");
        JRadioInspecionador.setEnabled(false);
        JRadioInspecionador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRadioInspecionadorActionPerformed(evt);
            }
        });

        JRadioOficialDia.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        JRadioOficialDia.setText("Oficial de Dia");
        JRadioOficialDia.setEnabled(false);
        JRadioOficialDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRadioOficialDiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jRadioArmeiro)
                        .addGap(12, 12, 12)
                        .addComponent(JRadioInspecionador))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLoginMilitar)
                            .addComponent(jTidentidade, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JRadioOficialDia)
                    .addComponent(jBautenticar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabelLoginMilitar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTidentidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBautenticar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioArmeiro)
                        .addComponent(JRadioInspecionador))
                    .addComponent(JRadioOficialDia, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBcancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jBsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarActionPerformed
        try {
            FuncaoMilitar funcao = new FuncaoMilitar();
            FuncaoMilitarDao fdao = new FuncaoMilitarDao();
            Militar militar = new Militar();
            Funcao tipofuncao = new Funcao();
            System.out.println("" + idMilitar);
            militar.setId(idMilitar);
            funcao.setMilitar(militar);
            tipofuncao.setId(status());
            funcao.setFuncao(tipofuncao);
            fdao.Cadastrar(funcao);
            JOptionPane.showMessageDialog(null, "CADASTRADO");
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(TlCadFuncaoMilitar.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jBsalvarActionPerformed

    private void jBautenticarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBautenticarActionPerformed
        verificaLista();
    }//GEN-LAST:event_jBautenticarActionPerformed

    private void jRadioArmeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioArmeiroActionPerformed
        JRadioInspecionador.setEnabled(false);
        JRadioOficialDia.setEnabled(false);
    }//GEN-LAST:event_jRadioArmeiroActionPerformed

    private void JRadioInspecionadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRadioInspecionadorActionPerformed
        jRadioArmeiro.setEnabled(false);
        JRadioOficialDia.setEnabled(false);
    }//GEN-LAST:event_JRadioInspecionadorActionPerformed

    private void JRadioOficialDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRadioOficialDiaActionPerformed
        JRadioInspecionador.setEnabled(false);
        jRadioArmeiro.setEnabled(false);

    }//GEN-LAST:event_JRadioOficialDiaActionPerformed

    private void jTidentidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTidentidadeActionPerformed
        verificaIdentida();
    }//GEN-LAST:event_jTidentidadeActionPerformed

    private void verificaLista() {
        String Armeiro = "ARMEIRO";
        String Inspecionador = "INSPECIONADOR";
        String OficialDia = "OFICIAL DIA";
        try {
            List<FuncaoMilitar> lista = new FuncaoMilitarDao().buscaFuncoes(jTidentidade.getText());
            if (lista.isEmpty()) {
                JOptionPane.showMessageDialog(null, "MILITAR SEM FUNÇÃO");
            } else {
                jTidentidade.setEditable(false);
                jBsalvar.setEnabled(true);
                for (FuncaoMilitar f : lista) {
                    idMilitar = f.getMilitar().getId();
                    if (f.getFuncao().getFuncao().equals(Armeiro)) {
                        JOptionPane.showMessageDialog(this, "Militar já possui função de Armeiro");
                        jRadioArmeiro.setEnabled(false);

                    }
                    if (f.getFuncao().getFuncao().equals(Inspecionador)) {
                        JOptionPane.showMessageDialog(this, "Militar já possui função de Inspecionador");
                        JRadioInspecionador.setEnabled(false);

                    }
                    if (f.getFuncao().getFuncao().equals(OficialDia)) {
                        JOptionPane.showMessageDialog(this, "Militar já possui função de Oficial de Dia");
                        JRadioOficialDia.setEnabled(false);

                    } else {
                        jBsalvar.setEnabled(true);
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Armaria.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private int status() {
        int idFuncao = 1;
        if (JRadioInspecionador.isSelected()) {
            idFuncao = 2;
        }
        if (JRadioOficialDia.isSelected()) {
            idFuncao = 3;
        }
        return idFuncao;
    }

    private void verificaIdentida() {
        try {
            idMilitar = new MilitarDao().verificarIdentidade(jTidentidade.getText());
            if (idMilitar == null) {
                JOptionPane.showMessageDialog(null, "IDENTIDADE INCORRETA!");
                jTidentidade.setText("");
            } else {
                JRadioInspecionador.setEnabled(true);
                JRadioOficialDia.setEnabled(true);
                jRadioArmeiro.setEnabled(true);
                verificaLista();
                jBsalvar.setEnabled(true);
            }
            
        } catch (Exception ex) {
            Logger.getLogger(TlCadFuncaoMilitar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JRadioInspecionador;
    private javax.swing.JRadioButton JRadioOficialDia;
    private javax.swing.ButtonGroup StatusArmeiro;
    private javax.swing.ButtonGroup StatusInspecionador;
    private javax.swing.ButtonGroup StatusOficialDia;
    private javax.swing.JButton jBautenticar;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBsalvar;
    private javax.swing.JLabel jLabelLoginMilitar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioArmeiro;
    private javax.swing.JTextField jTidentidade;
    // End of variables declaration//GEN-END:variables
}
