/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view_TelaAlterar;

import armaria.Armaria;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.bean.FuncaoMilitar;
import model.dao.FuncaoMilitarDao;
import servicos.LimitaTexto;

/**
 *
 * @author ASUS
 */
public class TlAltFuncaoMilitar extends javax.swing.JInternalFrame {

    private Integer idArmeiro;
    private Integer idInspecionador;
    private Integer idOficialDia;

    public TlAltFuncaoMilitar() {
        initComponents();
        jTidentidade.setDocument(new LimitaTexto(10));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StatusArmeiro = new javax.swing.ButtonGroup();
        StatusInspecionador = new javax.swing.ButtonGroup();
        StatusOficialDia = new javax.swing.ButtonGroup();
        jBcancelar = new javax.swing.JButton();
        jBsalvar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanelOficialDia = new javax.swing.JPanel();
        jLstatus4 = new javax.swing.JLabel();
        jRadioBativooficialdia = new javax.swing.JRadioButton();
        jRadioBinativooficialdia = new javax.swing.JRadioButton();
        jPanelInspecionador = new javax.swing.JPanel();
        jLstatus2 = new javax.swing.JLabel();
        jRadioBativoinspecionador = new javax.swing.JRadioButton();
        jRadioBinativoinspecionador = new javax.swing.JRadioButton();
        jPanelArmeiro = new javax.swing.JPanel();
        jLstatus1 = new javax.swing.JLabel();
        jRadioBativoarmeiro = new javax.swing.JRadioButton();
        jRadioBinativoarmeiro = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jTidentidade = new javax.swing.JTextField();
        jLabelLoginMilitar = new javax.swing.JLabel();
        jBautenticar = new javax.swing.JButton();
        jRadioArmeiro = new javax.swing.JRadioButton();
        JRadioInspecionador = new javax.swing.JRadioButton();
        JRadioOficialDia = new javax.swing.JRadioButton();

        setBorder(null);
        setFrameIcon(null);

        jBcancelar.setBackground(new java.awt.Color(242, 67, 56));
        jBcancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/cancela32.png"))); // NOI18N
        jBcancelar.setText("CANCELAR");
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });

        jBsalvar.setBackground(new java.awt.Color(75, 184, 75));
        jBsalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/salvar.png"))); // NOI18N
        jBsalvar.setText("SALVAR");
        jBsalvar.setEnabled(false);
        jBsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanelOficialDia.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Função Oficial de Dia", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16))); // NOI18N
        jPanelOficialDia.setEnabled(false);

        jLstatus4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLstatus4.setText("Status:");

        StatusOficialDia.add(jRadioBativooficialdia);
        jRadioBativooficialdia.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadioBativooficialdia.setText("Ativo");
        jRadioBativooficialdia.setEnabled(false);

        StatusOficialDia.add(jRadioBinativooficialdia);
        jRadioBinativooficialdia.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadioBinativooficialdia.setText("Inativo");
        jRadioBinativooficialdia.setEnabled(false);

        javax.swing.GroupLayout jPanelOficialDiaLayout = new javax.swing.GroupLayout(jPanelOficialDia);
        jPanelOficialDia.setLayout(jPanelOficialDiaLayout);
        jPanelOficialDiaLayout.setHorizontalGroup(
            jPanelOficialDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOficialDiaLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLstatus4)
                .addGap(18, 18, 18)
                .addComponent(jRadioBativooficialdia)
                .addGap(42, 42, 42)
                .addComponent(jRadioBinativooficialdia)
                .addContainerGap(215, Short.MAX_VALUE))
        );
        jPanelOficialDiaLayout.setVerticalGroup(
            jPanelOficialDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOficialDiaLayout.createSequentialGroup()
                .addGroup(jPanelOficialDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLstatus4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelOficialDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioBativooficialdia)
                        .addComponent(jRadioBinativooficialdia)))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        jPanelInspecionador.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Função Inspecionador", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16))); // NOI18N
        jPanelInspecionador.setEnabled(false);

        jLstatus2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLstatus2.setText("Status:");

        StatusInspecionador.add(jRadioBativoinspecionador);
        jRadioBativoinspecionador.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadioBativoinspecionador.setText("Ativo");
        jRadioBativoinspecionador.setEnabled(false);

        StatusInspecionador.add(jRadioBinativoinspecionador);
        jRadioBinativoinspecionador.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadioBinativoinspecionador.setText("Inativo");
        jRadioBinativoinspecionador.setEnabled(false);

        javax.swing.GroupLayout jPanelInspecionadorLayout = new javax.swing.GroupLayout(jPanelInspecionador);
        jPanelInspecionador.setLayout(jPanelInspecionadorLayout);
        jPanelInspecionadorLayout.setHorizontalGroup(
            jPanelInspecionadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInspecionadorLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLstatus2)
                .addGap(18, 18, 18)
                .addComponent(jRadioBativoinspecionador)
                .addGap(42, 42, 42)
                .addComponent(jRadioBinativoinspecionador)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanelInspecionadorLayout.setVerticalGroup(
            jPanelInspecionadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInspecionadorLayout.createSequentialGroup()
                .addGroup(jPanelInspecionadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLstatus2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelInspecionadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioBativoinspecionador)
                        .addComponent(jRadioBinativoinspecionador)))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanelArmeiro.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Função Armeiro ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16))); // NOI18N
        jPanelArmeiro.setEnabled(false);

        jLstatus1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLstatus1.setText("Status:");

        StatusArmeiro.add(jRadioBativoarmeiro);
        jRadioBativoarmeiro.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadioBativoarmeiro.setText("Ativo");
        jRadioBativoarmeiro.setEnabled(false);

        StatusArmeiro.add(jRadioBinativoarmeiro);
        jRadioBinativoarmeiro.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadioBinativoarmeiro.setText("Inativo");
        jRadioBinativoarmeiro.setEnabled(false);

        javax.swing.GroupLayout jPanelArmeiroLayout = new javax.swing.GroupLayout(jPanelArmeiro);
        jPanelArmeiro.setLayout(jPanelArmeiroLayout);
        jPanelArmeiroLayout.setHorizontalGroup(
            jPanelArmeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArmeiroLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLstatus1)
                .addGap(18, 18, 18)
                .addComponent(jRadioBativoarmeiro)
                .addGap(42, 42, 42)
                .addComponent(jRadioBinativoarmeiro)
                .addContainerGap(215, Short.MAX_VALUE))
        );
        jPanelArmeiroLayout.setVerticalGroup(
            jPanelArmeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArmeiroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelArmeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLstatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelArmeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioBativoarmeiro)
                        .addComponent(jRadioBinativoarmeiro)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados Função Militar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16))); // NOI18N

        jTidentidade.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jTidentidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTidentidadeActionPerformed(evt);
            }
        });

        jLabelLoginMilitar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelLoginMilitar.setText("IDENTIDADE:");

        jBautenticar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBautenticar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/pesquisar.png"))); // NOI18N
        jBautenticar.setBorder(null);
        jBautenticar.setBorderPainted(false);
        jBautenticar.setContentAreaFilled(false);
        jBautenticar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBautenticarActionPerformed(evt);
            }
        });

        jRadioArmeiro.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadioArmeiro.setText("Armeiro");
        jRadioArmeiro.setEnabled(false);
        jRadioArmeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioArmeiroActionPerformed(evt);
            }
        });

        JRadioInspecionador.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        JRadioInspecionador.setText("Inspecionador");
        JRadioInspecionador.setEnabled(false);
        JRadioInspecionador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRadioInspecionadorActionPerformed(evt);
            }
        });

        JRadioOficialDia.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        JRadioOficialDia.setText("Oficial de Dia");
        JRadioOficialDia.setEnabled(false);
        JRadioOficialDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRadioOficialDiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jRadioArmeiro))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelLoginMilitar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTidentidade, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JRadioInspecionador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JRadioOficialDia))
                    .addComponent(jBautenticar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBautenticar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabelLoginMilitar))
                                    .addComponent(jTidentidade))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioArmeiro)
                            .addComponent(JRadioInspecionador)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JRadioOficialDia)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOficialDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelInspecionador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelArmeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelArmeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelInspecionador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanelOficialDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBcancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jBsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jBsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarActionPerformed
        FuncaoMilitar funcao = new FuncaoMilitar();
        FuncaoMilitarDao fdao = new FuncaoMilitarDao();
        if (jRadioArmeiro.isSelected()) {
            funcao.setId(idArmeiro);
            funcao.setStatus(statusArmeiro());
        }
        if (JRadioInspecionador.isSelected()) {
            funcao.setId(idInspecionador);
            funcao.setStatus(statusInspecionador());
        }
        if (JRadioOficialDia.isSelected()) {
            funcao.setId(idOficialDia);
            funcao.setStatus(statusOficialDia());
        }
        try {
            fdao.alterar(funcao);
            JOptionPane.showMessageDialog(null, "ALTERADO");
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(TlAltFuncaoMilitar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBsalvarActionPerformed

    private void jBautenticarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBautenticarActionPerformed
        verificaLista();
    }//GEN-LAST:event_jBautenticarActionPerformed

    private void jRadioArmeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioArmeiroActionPerformed
        JRadioInspecionador.setEnabled(false);
        jRadioBativooficialdia.setEnabled(false);
        jPanelArmeiro.setEnabled(true);
        jRadioBativoarmeiro.setEnabled(true);
        jRadioBinativoarmeiro.setEnabled(true);
        jBsalvar.setEnabled(true);
    }//GEN-LAST:event_jRadioArmeiroActionPerformed

    private void JRadioInspecionadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRadioInspecionadorActionPerformed
        jRadioArmeiro.setEnabled(false);
        JRadioOficialDia.setEnabled(false);
        jPanelInspecionador.setEnabled(true);
        jRadioBativoinspecionador.setEnabled(true);
        jRadioBinativoinspecionador.setEnabled(true);
        jBsalvar.setEnabled(true);
    }//GEN-LAST:event_JRadioInspecionadorActionPerformed

    private void JRadioOficialDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRadioOficialDiaActionPerformed
        JRadioInspecionador.setEnabled(false);
        jRadioArmeiro.setEnabled(false);
        jPanelOficialDia.setEnabled(true);
        jRadioBativooficialdia.setEnabled(true);
        jRadioBinativooficialdia.setEnabled(true);
        jBsalvar.setEnabled(true);
    }//GEN-LAST:event_JRadioOficialDiaActionPerformed

    private void jTidentidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTidentidadeActionPerformed
        verificaLista();
    }//GEN-LAST:event_jTidentidadeActionPerformed

    private void verificaLista() {
        String Armeiro = "ARMEIRO";
        String Inspecionador = "INSPECIONADOR";
        String OficialDia = "OFICIAL DIA";
        String Ativo = "ATIVO";
        String Inativo = "INATIVO";
        try {
            List<FuncaoMilitar> lista = new FuncaoMilitarDao().buscaFuncoes(jTidentidade.getText());
            if (lista.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Militar sem função");
                jTidentidade.setText("");
            } else {
                jTidentidade.setEditable(false);
                for (FuncaoMilitar f : lista) {

                    if (f.getFuncao().getFuncao().equals(Armeiro) && f.getStatus().equals(Ativo)) {
                        JOptionPane.showMessageDialog(null, "FUNÇÃO ARMEIRO - ATIVO");
                        idArmeiro = f.getId();
                        jRadioBativoarmeiro.setSelected(true);
                        jRadioArmeiro.setEnabled(true);
                    }
                    if (f.getFuncao().getFuncao().equals(Armeiro) && f.getStatus().equals(Inativo)) {
                        JOptionPane.showMessageDialog(null, "FUNÇÃO ARMEIRO - INATIVO");
                        idArmeiro = f.getId();
                        jRadioBinativoarmeiro.setSelected(true);
                        jRadioArmeiro.setEnabled(true);
                    }
                    if (f.getFuncao().getFuncao().equals(Inspecionador) && f.getStatus().equals(Ativo)) {
                        JOptionPane.showMessageDialog(null, "FUNÇÃO INSPECIONADOR - ATIVO");
                        idInspecionador = f.getId();
                        jRadioBativoinspecionador.setSelected(true);
                        JRadioInspecionador.setEnabled(true);

                    }
                    if (f.getFuncao().getFuncao().equals(Inspecionador) && f.getStatus().equals(Inativo)) {
                        JOptionPane.showMessageDialog(null, "FUNÇÃO INSPECIONADOR - INATIVO");
                        idInspecionador = f.getId();
                        jRadioBinativoinspecionador.setSelected(true);
                        JRadioInspecionador.setEnabled(true);

                    }
                    if (f.getFuncao().getFuncao().equals(OficialDia) && f.getStatus().equals(Ativo)) {
                        JOptionPane.showMessageDialog(null, "FUNÇÃO OFICIAL DIA - ATIVO");
                        idOficialDia = f.getId();
                        jRadioBativooficialdia.setSelected(true);
                        JRadioOficialDia.setEnabled(true);
                    }
                    if (f.getFuncao().getFuncao().equals(OficialDia) && f.getStatus().equals(Inativo)) {
                        JOptionPane.showMessageDialog(null, "FUNÇÃO OFICIAL DIA - INATIVO");
                        idOficialDia = f.getId();
                        jRadioBinativooficialdia.setSelected(true);
                        JRadioOficialDia.setEnabled(true);
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Armaria.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private String statusArmeiro() {
        String status = "ATIVO";
        if (jRadioBinativoarmeiro.isSelected()) {
            status = "INATIVO";
        }
        return status;
    }

    private String statusInspecionador() {
        String status = "ATIVO";
        if (jRadioBinativoinspecionador.isSelected()) {
            status = "INATIVO";
        }
        return status;
    }

    private String statusOficialDia() {
        String status = "ATIVO";
        if (jRadioBinativooficialdia.isSelected()) {
            status = "INATIVO";
        }
        return status;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JRadioInspecionador;
    private javax.swing.JRadioButton JRadioOficialDia;
    private javax.swing.ButtonGroup StatusArmeiro;
    private javax.swing.ButtonGroup StatusInspecionador;
    private javax.swing.ButtonGroup StatusOficialDia;
    private javax.swing.JButton jBautenticar;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBsalvar;
    private javax.swing.JLabel jLabelLoginMilitar;
    private javax.swing.JLabel jLstatus1;
    private javax.swing.JLabel jLstatus2;
    private javax.swing.JLabel jLstatus4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelArmeiro;
    private javax.swing.JPanel jPanelInspecionador;
    private javax.swing.JPanel jPanelOficialDia;
    private javax.swing.JRadioButton jRadioArmeiro;
    private javax.swing.JRadioButton jRadioBativoarmeiro;
    private javax.swing.JRadioButton jRadioBativoinspecionador;
    private javax.swing.JRadioButton jRadioBativooficialdia;
    private javax.swing.JRadioButton jRadioBinativoarmeiro;
    private javax.swing.JRadioButton jRadioBinativoinspecionador;
    private javax.swing.JRadioButton jRadioBinativooficialdia;
    private javax.swing.JTextField jTidentidade;
    // End of variables declaration//GEN-END:variables
}
