/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view_TelaAlterar;

import Controller.ControllerOM;
import java.awt.Color;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.OM;
import model.dao.OMDao;
import servicos.Maiusculas;

/**
 *
 * @author ASUS
 */
public class TlAltOM extends javax.swing.JInternalFrame {

    /**
     * Creates new form TlCadOM
     */
    public TlAltOM() {
        initComponents();
        jTextBusca.setDocument(new Maiusculas());
        jTextOm.setDocument(new Maiusculas());
        jLIdOm.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonsalvar = new javax.swing.JButton();
        jButtoncanelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLIdOm = new javax.swing.JLabel();
        jTextBusca = new javax.swing.JTextField();
        jLbusca = new javax.swing.JLabel();
        jLabelOm = new javax.swing.JLabel();
        jTextOm = new javax.swing.JTextField();
        jButtonEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOM = new javax.swing.JTable();

        setBorder(null);
        setFrameIcon(null);

        jButtonsalvar.setBackground(new java.awt.Color(75, 184, 75));
        jButtonsalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/salvar.png"))); // NOI18N
        jButtonsalvar.setText("SALVAR");
        jButtonsalvar.setEnabled(false);
        jButtonsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsalvarActionPerformed(evt);
            }
        });

        jButtoncanelar.setBackground(new java.awt.Color(242, 67, 56));
        jButtoncanelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtoncanelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/cancela32.png"))); // NOI18N
        jButtoncanelar.setText("CANCELAR");
        jButtoncanelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncanelarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados Organização Militar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16))); // NOI18N

        jLIdOm.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLIdOm.setText("IDOM");

        jTextBusca.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextBuscaKeyReleased(evt);
            }
        });

        jLbusca.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLbusca.setText("Pesquisar:");

        jLabelOm.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelOm.setText("Org. Militar:");

        jTextOm.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextOm.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(199, 199, 199)
                        .addComponent(jLIdOm, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextOm, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelOm, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLIdOm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelOm)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextOm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonEditar.setBackground(new java.awt.Color(244, 199, 109));
        jButtonEditar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/edit.png"))); // NOI18N
        jButtonEditar.setText("EDITAR");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jTableOM.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableOM.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jTableOM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ORGANIZAÇAO MILITAR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableOM.setRowHeight(30);
        jTableOM.getTableHeader().setReorderingAllowed(false);
        jTableOM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableOMMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableOM);
        if (jTableOM.getColumnModel().getColumnCount() > 0) {
            jTableOM.getColumnModel().getColumn(0).setMinWidth(0);
            jTableOM.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTableOM.getColumnModel().getColumn(0).setMaxWidth(0);
            jTableOM.getColumnModel().getColumn(1).setResizable(false);
            jTableOM.getColumnModel().getColumn(1).setPreferredWidth(900);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtoncanelar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtoncanelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonsalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsalvarActionPerformed
        OM om = new OM();
        ControllerOM controle = new ControllerOM();

        om.setOm(jTextOm.getText());
        om.setId(Integer.parseInt(jLIdOm.getText()));

        try {
            if (validarCampos() == false) {
                JOptionPane.showMessageDialog(null, "CAMPO OBRIGATÓRIO");
                jLIdOm.setForeground(Color.red);
            } else {
                controle.altetar(om);
                JOptionPane.showMessageDialog(null, "OM ALTERADA");
                dispose();
            }
        } catch (Exception ex) {
            Logger.getLogger(TlAltOM.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonsalvarActionPerformed

    private void jButtoncanelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncanelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtoncanelarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        jButtonsalvar.setEnabled(true);
        jTextOm.setEnabled(true);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jTextBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextBuscaKeyReleased
        if (jTextBusca.getText().length() == 0) {
            DefaultTableModel tabela = (DefaultTableModel) jTableOM.getModel();
            tabela.setNumRows(0);
        } else {
            listaBairro();
        }
    }//GEN-LAST:event_jTextBuscaKeyReleased

    private void jTableOMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableOMMouseClicked
        if(evt.getClickCount() == 2){
        int linha = jTableOM.getSelectedRow();
        jLIdOm.setText(String.valueOf(jTableOM.getValueAt(linha, 0)));
        jTextOm.setText(String.valueOf(jTableOM.getValueAt(linha, 1)));
        jButtonEditar.setEnabled(true);
        }
    }//GEN-LAST:event_jTableOMMouseClicked

    private void limparCampos() {
        jTextBusca.setText("");
    }

    private boolean validarCampos() {
        boolean valida = true;
        if (jTextOm.getText().equals("")) {
            valida = false;
        }
        return valida;
    }

    private void listaBairro() {
        DefaultTableModel tabela = (DefaultTableModel) jTableOM.getModel();
        tabela.setNumRows(0);
        String nome = jTextBusca.getText();
        OMDao omDao = new OMDao();
        List<OM> lista;

        try {
            lista = omDao.listaOmPorNome(nome);
            for (OM om : lista) {
                tabela.addRow(new Object[]{om.getId(), om.getOm()});
            }
        } catch (Exception ex) {
            System.out.println("Erro ao listar OM" + ex.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtoncanelar;
    private javax.swing.JButton jButtonsalvar;
    private javax.swing.JLabel jLIdOm;
    private javax.swing.JLabel jLabelOm;
    private javax.swing.JLabel jLbusca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableOM;
    private javax.swing.JTextField jTextBusca;
    private javax.swing.JTextField jTextOm;
    // End of variables declaration//GEN-END:variables

    
}
