/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view_TelaPesq;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.ClipboardOwner;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Militar;
import model.dao.MilitarDao;
import servicos.Maiusculas;

/**
 *
 * @author Asus
 */
public class TlPesqMilitar extends javax.swing.JInternalFrame {

    int contador;
    String status;
    
    public TlPesqMilitar() {
        initComponents();
        jTextBusca.setDocument(new Maiusculas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableMilitar = new javax.swing.JTable();
        jLSelecioneFiltro = new javax.swing.JLabel();
        jRadioButtonStatusAtivo = new javax.swing.JRadioButton();
        jRadioButtonStatusInativo = new javax.swing.JRadioButton();
        jTextBusca = new javax.swing.JTextField();
        jLbusca = new javax.swing.JLabel();
        jButtoncanelar2 = new javax.swing.JButton();
        jTtotal = new javax.swing.JTextField();
        jLTotal = new javax.swing.JLabel();
        jButtoncanelar3 = new javax.swing.JButton();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Buscar Militar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jTableMilitar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTableMilitar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identidade ", "Nome Completo", "Nome de Guerra"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMilitar.setRowHeight(30);
        jTableMilitar.setRowMargin(10);
        jTableMilitar.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(jTableMilitar);
        if (jTableMilitar.getColumnModel().getColumnCount() > 0) {
            jTableMilitar.getColumnModel().getColumn(0).setMinWidth(100);
            jTableMilitar.getColumnModel().getColumn(0).setMaxWidth(150);
            jTableMilitar.getColumnModel().getColumn(1).setPreferredWidth(500);
            jTableMilitar.getColumnModel().getColumn(2).setMinWidth(100);
            jTableMilitar.getColumnModel().getColumn(2).setPreferredWidth(150);
        }

        jLSelecioneFiltro.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLSelecioneFiltro.setText("Status:");

        buttonGroup1.add(jRadioButtonStatusAtivo);
        jRadioButtonStatusAtivo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadioButtonStatusAtivo.setText("Ativo");
        jRadioButtonStatusAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonStatusAtivoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonStatusInativo);
        jRadioButtonStatusInativo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadioButtonStatusInativo.setText("Inativo");
        jRadioButtonStatusInativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonStatusInativoActionPerformed(evt);
            }
        });

        jTextBusca.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextBuscaKeyReleased(evt);
            }
        });

        jLbusca.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLbusca.setText("Nome:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLSelecioneFiltro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonStatusAtivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonStatusInativo))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLbusca)
                                .addGap(18, 18, 18)
                                .addComponent(jTextBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 429, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSelecioneFiltro)
                    .addComponent(jRadioButtonStatusAtivo)
                    .addComponent(jRadioButtonStatusInativo))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );

        jButtoncanelar2.setBackground(new java.awt.Color(242, 67, 56));
        jButtoncanelar2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtoncanelar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/cancela32.png"))); // NOI18N
        jButtoncanelar2.setText("CANCELAR");
        jButtoncanelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncanelar2ActionPerformed(evt);
            }
        });

        jTtotal.setEditable(false);
        jTtotal.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTtotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTtotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLTotal.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLTotal.setText("TOTAL:");

        jButtoncanelar3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButtoncanelar3.setText("COPIAR IDENTIDADE");
        jButtoncanelar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncanelar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLTotal)
                        .addGap(18, 18, 18)
                        .addComponent(jTtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(456, 456, 456)
                        .addComponent(jButtoncanelar3)
                        .addGap(18, 18, 18)
                        .addComponent(jButtoncanelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtoncanelar2)
                        .addComponent(jButtoncanelar3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonStatusAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonStatusAtivoActionPerformed
        String status = "Ativo";
        List<Militar> lista;
        DefaultTableModel tabela = (DefaultTableModel) jTableMilitar.getModel();
        try {
            lista = new MilitarDao().pesqMilitarStatus(status);
            if (lista.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Não militar ativo");
                tabela.setNumRows(0);
            } else {
                tabela.setNumRows(0);
                contador = 0;
                for (Militar mil : lista) {
                    tabela.addRow(new Object[]{
                        mil.getIdmilitar(),
                        mil.getNome(),
                        mil.getLogin(),});
                contador ++;    
                jTtotal.setText(String.valueOf(contador));
                }
            }
        } catch (Exception ex) {
            System.out.println("Erro ao carregar lista de indisponivel" + ex.getMessage());
        }
    }//GEN-LAST:event_jRadioButtonStatusAtivoActionPerformed

    private void jRadioButtonStatusInativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonStatusInativoActionPerformed
        String status = "Inativo";
        List<Militar> lista;
        DefaultTableModel tabela = (DefaultTableModel) jTableMilitar.getModel();
        try {
            lista = new MilitarDao().pesqMilitarStatus(status);
            if (lista.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Não existe militar inativo");
                tabela.setNumRows(0);
            } else {
                contador = 0;
                tabela.setNumRows(0);
                for (Militar mil : lista) {

                    tabela.addRow(new Object[]{
                        mil.getIdmilitar(),
                        mil.getNome(),
                        mil.getLogin(),});
                contador ++;
                jTtotal.setText(String.valueOf(contador));
                }
            }
        } catch (Exception ex) {
            System.out.println("Erro ao carregar lista de indisponivel" + ex.getMessage());
        }
    }//GEN-LAST:event_jRadioButtonStatusInativoActionPerformed

    private void jButtoncanelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncanelar2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButtoncanelar2ActionPerformed

    private void jTextBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextBuscaKeyReleased
        if (jTextBusca.getText().length() == 0) {
            DefaultTableModel tabela = (DefaultTableModel) jTableMilitar.getModel();
            tabela.setNumRows(0);
        } else {
        listaMilitar();
        }
    }//GEN-LAST:event_jTextBuscaKeyReleased

    private void jButtoncanelar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncanelar3ActionPerformed
        pegaIdentidade();
    }//GEN-LAST:event_jButtoncanelar3ActionPerformed

    private void listaMilitar(){
        DefaultTableModel tabela = (DefaultTableModel) jTableMilitar.getModel();
        tabela.setNumRows(0);
        String nome = jTextBusca.getText();
        MilitarDao dao = new MilitarDao();
        List<Militar> lista;

        try {
            lista = dao.listaMilitarPorNome(nome,status());
            for (Militar mil : lista) {
                tabela.addRow(new Object[]{mil.getIdmilitar(), mil.getNome(), mil.getLogin()});
            }
        } catch (Exception ex) {
            System.out.println("Erro ao listar militar" + ex.getMessage());
        }
    }
    
    private String status(){
        if(jRadioButtonStatusAtivo.isSelected()){
            status = "ATIVO";
        }else{
            status = "INATIVO";
        }
        
        return status;
    }
    
 private void pegaIdentidade() {
        DefaultTableModel tabela = (DefaultTableModel) jTableMilitar.getModel();
        int linha = jTableMilitar.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(null, "SELECIONE UMA LINHA PARA COPIAR");
        } else {
            
            Clipboard boar = Toolkit.getDefaultToolkit().getSystemClipboard();
            ClipboardOwner selecao = new StringSelection((String) tabela.getValueAt(linha, 0));
            boar.setContents((Transferable)selecao, selecao);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtoncanelar2;
    private javax.swing.JButton jButtoncanelar3;
    private javax.swing.JLabel jLSelecioneFiltro;
    private javax.swing.JLabel jLTotal;
    private javax.swing.JLabel jLbusca;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonStatusAtivo;
    private javax.swing.JRadioButton jRadioButtonStatusInativo;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTableMilitar;
    private javax.swing.JTextField jTextBusca;
    private javax.swing.JTextField jTtotal;
    // End of variables declaration//GEN-END:variables
}
