/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view_TelaPesq;

import Controller.ControllerEquipamento;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Equipamento;
import model.dao.EquipamentoDao;
import servicos.Maiusculas;

/**
 *
 * @author Asus
 */
public class TlPesqArm extends javax.swing.JInternalFrame {

    int contador;

    public TlPesqArm() {
        initComponents();
        setTitle("Pesquisar Cautelas");
        jTpesquisa.setDocument(new Maiusculas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroupMaterial = new javax.swing.ButtonGroup();
        jButtoncanelar2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTabelaPesquisa = new javax.swing.JTable();
        jLPesqArmament = new javax.swing.JLabel();
        jLPesqTodosArmamento = new javax.swing.JLabel();
        jRadioButtonNome = new javax.swing.JRadioButton();
        jRadioButtonSerie = new javax.swing.JRadioButton();
        jTpesquisa = new javax.swing.JTextField();
        jRadioButtonDisponivel = new javax.swing.JRadioButton();
        jRadioButtonRecolhido = new javax.swing.JRadioButton();
        jRadioButtonIndisponivel = new javax.swing.JRadioButton();
        jRadioButtonArma = new javax.swing.JRadioButton();
        jRadioButtonFabricante = new javax.swing.JRadioButton();
        jRadioButtonCalibre = new javax.swing.JRadioButton();
        jLPesqArmament1 = new javax.swing.JLabel();
        jLPesqTodosArmamento1 = new javax.swing.JLabel();
        jRadioButtonCarga = new javax.swing.JRadioButton();
        jRadioButtonRelacionado = new javax.swing.JRadioButton();
        jRadioButtonParticular = new javax.swing.JRadioButton();
        jTtotal = new javax.swing.JTextField();
        jLTotal = new javax.swing.JLabel();

        jButtoncanelar2.setBackground(new java.awt.Color(242, 67, 56));
        jButtoncanelar2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtoncanelar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/cancela32.png"))); // NOI18N
        jButtoncanelar2.setText("CANCELAR");
        jButtoncanelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncanelar2ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Buscar Equipamentos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16))); // NOI18N

        jTabelaPesquisa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTabelaPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Equipamento", "Série", "Arma", "Calibre", "Fabricante", "Qtd", "Status ", "Obs"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabelaPesquisa.setToolTipText("");
        jTabelaPesquisa.setRowHeight(22);
        jTabelaPesquisa.setRowMargin(5);
        jTabelaPesquisa.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTabelaPesquisa);
        if (jTabelaPesquisa.getColumnModel().getColumnCount() > 0) {
            jTabelaPesquisa.getColumnModel().getColumn(0).setPreferredWidth(150);
            jTabelaPesquisa.getColumnModel().getColumn(0).setMaxWidth(150);
            jTabelaPesquisa.getColumnModel().getColumn(1).setMinWidth(120);
            jTabelaPesquisa.getColumnModel().getColumn(1).setPreferredWidth(120);
            jTabelaPesquisa.getColumnModel().getColumn(1).setMaxWidth(120);
            jTabelaPesquisa.getColumnModel().getColumn(2).setPreferredWidth(180);
            jTabelaPesquisa.getColumnModel().getColumn(2).setMaxWidth(180);
            jTabelaPesquisa.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTabelaPesquisa.getColumnModel().getColumn(3).setMaxWidth(100);
            jTabelaPesquisa.getColumnModel().getColumn(4).setMinWidth(120);
            jTabelaPesquisa.getColumnModel().getColumn(4).setPreferredWidth(120);
            jTabelaPesquisa.getColumnModel().getColumn(4).setMaxWidth(120);
            jTabelaPesquisa.getColumnModel().getColumn(5).setPreferredWidth(30);
            jTabelaPesquisa.getColumnModel().getColumn(5).setMaxWidth(30);
            jTabelaPesquisa.getColumnModel().getColumn(6).setPreferredWidth(100);
            jTabelaPesquisa.getColumnModel().getColumn(6).setMaxWidth(100);
        }

        jLPesqArmament.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLPesqArmament.setText("Digita:");

        jLPesqTodosArmamento.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLPesqTodosArmamento.setText("Status Equipamento:");

        buttonGroup1.add(jRadioButtonNome);
        jRadioButtonNome.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadioButtonNome.setText("Nome");

        buttonGroup1.add(jRadioButtonSerie);
        jRadioButtonSerie.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadioButtonSerie.setText("Nº Série");

        jTpesquisa.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTpesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTpesquisaKeyReleased(evt);
            }
        });

        buttonGroup1.add(jRadioButtonDisponivel);
        jRadioButtonDisponivel.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadioButtonDisponivel.setText("Disponível");
        jRadioButtonDisponivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDisponivelActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonRecolhido);
        jRadioButtonRecolhido.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadioButtonRecolhido.setText("Recolhido");
        jRadioButtonRecolhido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRecolhidoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonIndisponivel);
        jRadioButtonIndisponivel.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadioButtonIndisponivel.setText("Indisponível");
        jRadioButtonIndisponivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonIndisponivelActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonArma);
        jRadioButtonArma.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadioButtonArma.setText("Arma");

        buttonGroup1.add(jRadioButtonFabricante);
        jRadioButtonFabricante.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadioButtonFabricante.setText("Fabricante");

        buttonGroup1.add(jRadioButtonCalibre);
        jRadioButtonCalibre.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadioButtonCalibre.setText("Calibre");

        jLPesqArmament1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLPesqArmament1.setText("Selecione Filtro:");

        jLPesqTodosArmamento1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLPesqTodosArmamento1.setText("Material:");

        buttonGroup1.add(jRadioButtonCarga);
        jRadioButtonCarga.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadioButtonCarga.setText("Carga");
        jRadioButtonCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCargaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonRelacionado);
        jRadioButtonRelacionado.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadioButtonRelacionado.setText("Relacionado");
        jRadioButtonRelacionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRelacionadoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonParticular);
        jRadioButtonParticular.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadioButtonParticular.setText("Particular");
        jRadioButtonParticular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonParticularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLPesqTodosArmamento)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonDisponivel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonIndisponivel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonRecolhido))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLPesqArmament1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonNome)
                                .addGap(20, 20, 20)
                                .addComponent(jRadioButtonSerie)
                                .addGap(20, 20, 20)
                                .addComponent(jRadioButtonFabricante)
                                .addGap(20, 20, 20)
                                .addComponent(jRadioButtonArma)
                                .addGap(20, 20, 20)
                                .addComponent(jRadioButtonCalibre))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLPesqArmament)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLPesqTodosArmamento1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonCarga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonRelacionado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonParticular)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonNome)
                    .addComponent(jRadioButtonSerie)
                    .addComponent(jRadioButtonArma)
                    .addComponent(jRadioButtonFabricante)
                    .addComponent(jRadioButtonCalibre)
                    .addComponent(jLPesqArmament1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLPesqArmament)
                    .addComponent(jTpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonDisponivel)
                        .addComponent(jRadioButtonIndisponivel)
                        .addComponent(jRadioButtonRecolhido))
                    .addComponent(jLPesqTodosArmamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPesqTodosArmamento1)
                    .addComponent(jRadioButtonCarga)
                    .addComponent(jRadioButtonRelacionado)
                    .addComponent(jRadioButtonParticular))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTtotal.setEditable(false);
        jTtotal.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTtotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTtotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLTotal.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLTotal.setText("TOTAL:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtoncanelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtoncanelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtoncanelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncanelar2ActionPerformed
        dispose();
        jTpesquisa.setDocument(new Maiusculas());
    }//GEN-LAST:event_jButtoncanelar2ActionPerformed

    private void jTpesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTpesquisaKeyReleased
        if (jTpesquisa.getText().length() == 0) {
            DefaultTableModel tabela = (DefaultTableModel) jTabelaPesquisa.getModel();
            tabela.setNumRows(0);
        } else {
            if (pesquisaTipo() == true) {
                pesquisar();
            }

        }
    }//GEN-LAST:event_jTpesquisaKeyReleased

    private void jRadioButtonDisponivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDisponivelActionPerformed
        buscaEqpPorStatus();
    }//GEN-LAST:event_jRadioButtonDisponivelActionPerformed

    private void jRadioButtonRecolhidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRecolhidoActionPerformed
        buscaEqpPorStatus();
    }//GEN-LAST:event_jRadioButtonRecolhidoActionPerformed

    private void jRadioButtonIndisponivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonIndisponivelActionPerformed
        buscaEqpPorStatus();
    }//GEN-LAST:event_jRadioButtonIndisponivelActionPerformed

    private void jRadioButtonCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCargaActionPerformed
        buscaMaterial();
    }//GEN-LAST:event_jRadioButtonCargaActionPerformed

    private void jRadioButtonRelacionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRelacionadoActionPerformed
        buscaMaterial();
    }//GEN-LAST:event_jRadioButtonRelacionadoActionPerformed

    private void jRadioButtonParticularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonParticularActionPerformed
        buscaMaterial();
    }//GEN-LAST:event_jRadioButtonParticularActionPerformed

    String nome = null, serie = null, arma = null, fabricante = null, calibre = null;

    private boolean pesquisaTipo() {
        boolean retorno = false;
        if (jRadioButtonSerie.isSelected()) {
            serie = jTpesquisa.getText();
            nome = null;
            arma = null;
            fabricante = null;
            calibre = null;
            retorno = true;
        } else if (jRadioButtonNome.isSelected()) {
            nome = jTpesquisa.getText();
            serie = null;
            arma = null;
            fabricante = null;
            calibre = null;
            retorno = true;
        } else if (jRadioButtonFabricante.isSelected()) {
            fabricante = jTpesquisa.getText();
            nome = null;
            arma = null;
            serie = null;
            calibre = null;
            retorno = true;
        } else if (jRadioButtonArma.isSelected()) {
            arma = jTpesquisa.getText();
            nome = null;
            serie = null;
            fabricante = null;
            calibre = null;
            retorno = true;
        } else if (jRadioButtonCalibre.isSelected()) {
            DefaultTableModel tabela = (DefaultTableModel) jTabelaPesquisa.getModel();
            tabela.setNumRows(0);
            calibre = jTpesquisa.getText();
            nome = null;
            arma = null;
            fabricante = null;
            serie = null;
            retorno = true;
        }
        return retorno;
    }

    private void pesquisar() {

        if (pesquisaTipo() == true) {

            try {
                List<Equipamento> lista;
                lista = new ControllerEquipamento().listarEquipamentoPorFiltro(nome, serie, arma, fabricante, calibre);
                DefaultTableModel tabela = (DefaultTableModel) jTabelaPesquisa.getModel();
                contador = 0;
                tabela.setNumRows(0);
                for (Equipamento eqp : lista) {
                    tabela.addRow(new Object[]{
                        eqp.getNome(),
                        eqp.getSerie(),
                        eqp.getArma().getArma(),
                        eqp.getCalibre().getCalibre(),
                        eqp.getFabricante().getFabricante(),
                        eqp.getQtd(),
                        eqp.getStatus(),
                        eqp.getObs(),});
                    contador++;
                    jTtotal.setText(String.valueOf(contador));
                }
            } catch (Exception ex) {
                System.out.println("Erro ao Pesquisar Armamento " + ex.getMessage());;
            }

        } else {
            JOptionPane.showMessageDialog(null, "ESCOLHA UM FILTRO");
        }
    }

    private String statusEqp() {
        String material = null;
        if (jRadioButtonDisponivel.isSelected()) {
            material = "DISPONIVEL";
        }
        if (jRadioButtonIndisponivel.isSelected()) {
            material = "INDISPONIVEl";
        }
        if (jRadioButtonRecolhido.isSelected()) {
            material = "RECOLHIDO";
        }
        return material;
    }

    private void buscaEqpPorStatus() {
        List<Equipamento> lista;
        try {
            lista = new EquipamentoDao().listEquipamentoPorStatus(statusEqp());
            DefaultTableModel tabela = (DefaultTableModel) jTabelaPesquisa.getModel();
            if (lista.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Não existe cautelas");
                tabela.setNumRows(0);
            } else {
                contador = 0;
                tabela.setNumRows(0);
                for (Equipamento e : lista) {
                    tabela.addRow(new Object[]{
                        e.getNome(),
                        e.getSerie(),
                        e.getArma().getArma(),
                        e.getCalibre().getCalibre(),
                        e.getFabricante().getFabricante(),
                        e.getQtd(),
                        e.getStatus(),
                        e.getObs(),});
                    contador++;
                    jTtotal.setText(String.valueOf(contador));
                }
            }
        } catch (Exception ex) {
            System.out.println("Erro ao carregar lista de indisponivel" + ex.getMessage());
        }
    }

    private String tipoMaterial() {
        String material = null;
        if (jRadioButtonCarga.isSelected()) {
            material = "CARGA";
        }
        if (jRadioButtonRelacionado.isSelected()) {
            material = "RELACIONADO";
        }
        if (jRadioButtonParticular.isSelected()) {
            material = "PARTICULAR";
        }
        return material;
    }

    private void buscaMaterial() {
        List<Equipamento> lista;
        try {
            lista = new EquipamentoDao().listEquipamentoTipoMaterial(tipoMaterial());
            DefaultTableModel tabela = (DefaultTableModel) jTabelaPesquisa.getModel();
            if (lista.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Não existe cautelas");
                tabela.setNumRows(0);
            } else {
                contador = 0;
                tabela.setNumRows(0);
                for (Equipamento e : lista) {
                    tabela.addRow(new Object[]{
                        e.getNome(),
                        e.getSerie(),
                        e.getArma().getArma(),
                        e.getCalibre().getCalibre(),
                        e.getFabricante().getFabricante(),
                        e.getQtd(),
                        e.getStatus(),
                        e.getObs(),});
                    contador++;
                    jTtotal.setText(String.valueOf(contador));
                }
            }
        } catch (Exception ex) {
            System.out.println("Erro ao carregar lista de indisponivel" + ex.getMessage());
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroupMaterial;
    private javax.swing.JButton jButtoncanelar2;
    private javax.swing.JLabel jLPesqArmament;
    private javax.swing.JLabel jLPesqArmament1;
    private javax.swing.JLabel jLPesqTodosArmamento;
    private javax.swing.JLabel jLPesqTodosArmamento1;
    private javax.swing.JLabel jLTotal;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonArma;
    private javax.swing.JRadioButton jRadioButtonCalibre;
    private javax.swing.JRadioButton jRadioButtonCarga;
    private javax.swing.JRadioButton jRadioButtonDisponivel;
    private javax.swing.JRadioButton jRadioButtonFabricante;
    private javax.swing.JRadioButton jRadioButtonIndisponivel;
    private javax.swing.JRadioButton jRadioButtonNome;
    private javax.swing.JRadioButton jRadioButtonParticular;
    private javax.swing.JRadioButton jRadioButtonRecolhido;
    private javax.swing.JRadioButton jRadioButtonRelacionado;
    private javax.swing.JRadioButton jRadioButtonSerie;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTabelaPesquisa;
    private javax.swing.JTextField jTpesquisa;
    private javax.swing.JTextField jTtotal;
    // End of variables declaration//GEN-END:variables
}
