/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view_TelaPesq;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.FuncaoMilitar;
import model.dao.FuncaoMilitarDao;

/**
 *
 * @author Asus
 */
public class TlPesqFuncao extends javax.swing.JInternalFrame {

    int contador;

    public TlPesqFuncao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTabelaMilitarFuncao = new javax.swing.JTable();
        jLSelecioneFiltro1 = new javax.swing.JLabel();
        jRadioButtonFuncaoInspecionador = new javax.swing.JRadioButton();
        jRadioButtonFuncaoArmeiro = new javax.swing.JRadioButton();
        jRadioButtonFuncaoOfdia = new javax.swing.JRadioButton();
        jButtoncanelar2 = new javax.swing.JButton();
        jTtotal = new javax.swing.JTextField();
        jLTotal = new javax.swing.JLabel();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Buscar Função", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16))); // NOI18N

        jTabelaMilitarFuncao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTabelaMilitarFuncao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome Completo", "Nome de Guerra", "Função", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabelaMilitarFuncao.setAutoscrolls(false);
        jTabelaMilitarFuncao.setRowHeight(22);
        jTabelaMilitarFuncao.setRowMargin(5);
        jTabelaMilitarFuncao.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(jTabelaMilitarFuncao);

        jLSelecioneFiltro1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLSelecioneFiltro1.setText("Função:");

        buttonGroup1.add(jRadioButtonFuncaoInspecionador);
        jRadioButtonFuncaoInspecionador.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadioButtonFuncaoInspecionador.setText("Inspecionador");
        jRadioButtonFuncaoInspecionador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFuncaoInspecionadorActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonFuncaoArmeiro);
        jRadioButtonFuncaoArmeiro.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadioButtonFuncaoArmeiro.setText("Armeiro");
        jRadioButtonFuncaoArmeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFuncaoArmeiroActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonFuncaoOfdia);
        jRadioButtonFuncaoOfdia.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRadioButtonFuncaoOfdia.setText("Oficial de Dia");
        jRadioButtonFuncaoOfdia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFuncaoOfdiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLSelecioneFiltro1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonFuncaoArmeiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonFuncaoInspecionador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonFuncaoOfdia)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(5, 5, 5))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSelecioneFiltro1)
                    .addComponent(jRadioButtonFuncaoArmeiro)
                    .addComponent(jRadioButtonFuncaoInspecionador)
                    .addComponent(jRadioButtonFuncaoOfdia))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtoncanelar2.setBackground(new java.awt.Color(242, 67, 56));
        jButtoncanelar2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtoncanelar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeSisArma/cancela32.png"))); // NOI18N
        jButtoncanelar2.setText("CANCELAR");
        jButtoncanelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncanelar2ActionPerformed(evt);
            }
        });

        jTtotal.setEditable(false);
        jTtotal.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTtotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTtotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLTotal.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLTotal.setText("TOTAL:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtoncanelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtoncanelar2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonFuncaoInspecionadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFuncaoInspecionadorActionPerformed
        String status = "Inspecionador";
        List<FuncaoMilitar> lista;
        DefaultTableModel tabela = (DefaultTableModel) jTabelaMilitarFuncao.getModel();
        try {
            lista = new FuncaoMilitarDao().pesqFuncao(status);
            if (lista.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Não existe militar com a função de armeiro");
                tabela.setNumRows(0);
            } else {
                contador = 0;
                tabela.setNumRows(0);
                for (FuncaoMilitar fun : lista) {
                    tabela.addRow(new Object[]{
                        fun.getMilitar().getNome(),
                        fun.getMilitar().getLogin(),
                        fun.getFuncao().getFuncao(),
                        fun.getStatus(),});
                    contador++;
                    jTtotal.setText(String.valueOf(contador));
                }
            }
        } catch (Exception ex) {
            System.out.println("Erro ao carregar lista de indisponivel" + ex.getMessage());
        }
    }//GEN-LAST:event_jRadioButtonFuncaoInspecionadorActionPerformed

    private void jRadioButtonFuncaoArmeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFuncaoArmeiroActionPerformed
        String status = "Armeiro";
        List<FuncaoMilitar> lista;
        DefaultTableModel tabela = (DefaultTableModel) jTabelaMilitarFuncao.getModel();
        try {
            lista = new FuncaoMilitarDao().pesqFuncao(status);
            if (lista.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Não existe militar com a função de armeiro");
                tabela.setNumRows(0);
            } else {
                contador = 0;
                tabela.setNumRows(0);
                for (FuncaoMilitar fun : lista) {

                    tabela.addRow(new Object[]{
                        fun.getMilitar().getNome(),
                        fun.getMilitar().getLogin(),
                        fun.getFuncao().getFuncao(),
                        fun.getStatus(),});
                    contador++;
                    jTtotal.setText(String.valueOf(contador));
                }
            }
        } catch (Exception ex) {
            System.out.println("Erro ao carregar lista de indisponivel" + ex.getMessage());
        }
    }//GEN-LAST:event_jRadioButtonFuncaoArmeiroActionPerformed

    private void jRadioButtonFuncaoOfdiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFuncaoOfdiaActionPerformed
        String status = "Oficial Dia";
        List<FuncaoMilitar> lista;
        DefaultTableModel tabela = (DefaultTableModel) jTabelaMilitarFuncao.getModel();
        try {
            lista = new FuncaoMilitarDao().pesqFuncao(status);
            if (lista.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Não existe militar com a função de armeiro");
                tabela.setNumRows(0);
            } else {
                contador = 0;
                tabela.setNumRows(0);
                for (FuncaoMilitar fun : lista) {

                    tabela.addRow(new Object[]{
                        fun.getMilitar().getNome(),
                        fun.getMilitar().getLogin(),
                        fun.getFuncao().getFuncao(),
                        fun.getStatus(),});
                    contador++;
                    jTtotal.setText(String.valueOf(contador));
                }
            }
        } catch (Exception ex) {
            System.out.println("Erro ao carregar lista de indisponivel" + ex.getMessage());
        }
    }//GEN-LAST:event_jRadioButtonFuncaoOfdiaActionPerformed

    private void jButtoncanelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncanelar2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButtoncanelar2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtoncanelar2;
    private javax.swing.JLabel jLSelecioneFiltro1;
    private javax.swing.JLabel jLTotal;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonFuncaoArmeiro;
    private javax.swing.JRadioButton jRadioButtonFuncaoInspecionador;
    private javax.swing.JRadioButton jRadioButtonFuncaoOfdia;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTabelaMilitarFuncao;
    private javax.swing.JTextField jTtotal;
    // End of variables declaration//GEN-END:variables
}
